-- Migration 20260522170000_drop_orphan_laplace_extension
--
-- Cleanup migration: drop the orphan 'laplace' extension left behind by the
-- pre-modularization layout (single-extension era, before PR #182 landed
-- the laplace_geom + laplace_substrate split per ADR 0025).
--
-- On hart-server's 'laplace' database, the OLD 'laplace' extension is still
-- in pg_extension from earlier sessions. The PR #182 migration installs
-- laplace_geom + laplace_substrate alongside it but does not drop it. The
-- old extension's functions reference $libdir/laplace which is no longer
-- produced by the new CMake build — leaving them in pg_extension creates
-- stale state visible in \dx and a foot-gun if any client calls the old
-- laplace_version() function.
--
-- Per RULES.md R9: clean
-- cutover, no backwards-compat layer. DROP CASCADE removes the orphan's
-- functions; the 'laplace' schema (declared by both old and new extensions
-- via schema='laplace') is owned by laplace_admin and survives the drop —
-- it's now owned by laplace_substrate's installation.
--
-- Idempotent: IF EXISTS no-ops when the orphan is absent (fresh DBs +
-- already-cleaned DBs).
--
-- Disk-side stale files (/usr/share/postgresql/18/extension/laplace.{control,sql}
-- + /usr/lib/postgresql/18/lib/laplace.so) are not removed by this migration
-- (DbUp is in-DB only). One-shot disk cleanup (run once on hart-server):
--   sudo rm -f /usr/share/postgresql/18/extension/laplace.control \
--              /usr/share/postgresql/18/extension/laplace--0.1.0.sql \
--              /usr/lib/postgresql/18/lib/laplace.so

DROP EXTENSION IF EXISTS laplace CASCADE;
