namespace Laplace.Endpoints.OpenAICompat;

internal sealed record ForwardObservedEvent(
    int Step,
    string Event,
    int RoutingRound,
    string EntityIdHex,
    string Entity,
    string? Surface,
    int StrideUsed,
    string RootIdHex,
    int CandidateCount = 0,
    int OrderedContextCount = 0,
    int ProposalChannelCount = 0,
    int ExactChannelCount = 0,
    long SequenceOccurrences = 0,
    int CoveredOccurrences = 0,
    int RelationFamilies = 0,
    int OpposedOccurrences = 0,
    string? SupportAnchorIdHex = null,
    string? SupportAnchor = null,
    string? SupportRelationIdHex = null,
    string? SupportRelation = null,
    bool? SupportOutbound = null,
    long? SupportRating = null,
    long? SupportRd = null,
    long? SupportWitnesses = null,
    int SupportSources = 0,
    int SupportContexts = 0,
    bool DeclaredResult = false,
    string? ProgramIdHex = null,
    int RequiredObligations = 0,
    int SatisfiedObligations = 0,
    int RemainingRequired = 0,
    bool Completion = false,
    string? Disposition = null,
    string? OutputFingerprintHex = null,
    string? SemanticActIdHex = null,
    int OutputCount = 0,
    IReadOnlyList<string>? PriorDiscourseIds = null);
