server {
    listen 8080;
    listen [::]:8080;
    server_name hart-server _;

    return 308 https://hart-server:8443$request_uri;

    access_log /var/log/nginx/laplace-access.log;
    error_log  /var/log/nginx/laplace-error.log;
}
