/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CapabilitiesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatCompletionsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatCompletionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Payment Required */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentRequiredResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompletionsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompletionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Payment Required */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentRequiredResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmbeddingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmbeddingsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Payment Required */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentRequiredResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{target}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number | string;
                };
                header?: never;
                path: {
                    target: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvidenceResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuditReportRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditReportResponse"];
                    };
                };
                /** @description Payment Required */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentRequiredResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/visualizations/substrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VisualizationExecuteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VisualizationGraphResponse"];
                    };
                };
                /** @description Payment Required */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentRequiredResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/explain/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExplainReportRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExplainReportResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Payment Required */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentRequiredResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillingCatalogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillingProductsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillingPlansResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/plans/{planId}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanSubscribeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanSubscribeResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntitlementsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/entitlements/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreditConsumeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreditConsumeResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Payment Required */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreditConsumeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/catalog/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogSyncResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BillingPreflightRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PreflightQuoteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/synthesis/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SynthesisQuoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SynthesisQuoteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/explain/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExplainQuoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExplainQuoteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/audit/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuditQuoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditQuoteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/visualization/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VisualizationQuoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VisualizationQuoteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/recipe/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecipeQuoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecipeQuoteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/quotes/{quoteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    quoteId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteStatusResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/legal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MoveRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/bestmove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BestMoveRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/train/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    temperature?: number | string;
                    weight?: number | string;
                    maxPlies?: number | string;
                    games?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/train/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/train/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/learned-pst": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/lab/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/lab/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LabStartRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/lab/stop/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/lab/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/lab/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/lab/jobs/{jobId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/lab/jobs/{jobId}/artifact/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chess/lab/jobs/{jobId}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditQuoteRequest: {
            tenant: null | string;
            scope?: null | string;
            /** @default true */
            include_evidence: boolean;
            /** @default true */
            include_consensus: boolean;
            /** @default true */
            include_convergence: boolean;
            /** @default false */
            academic: boolean;
        };
        AuditQuoteResponse: {
            quote_id: string;
            tenant: string;
            service_id: string;
            scope: string;
            academic: boolean;
            /** Format: int64 */
            metered_items: number | string;
            /** Format: int32 */
            billable_units: number | string;
            unit: string;
            /** Format: int64 */
            items_per_unit: number | string;
            /** Format: int64 */
            amount_cents: number | string;
            currency: string;
            status: string;
            /** Format: date-time */
            expires_at: string;
            stripe_checkout_url: null | string;
            next: components["schemas"]["QuoteNextStep"];
        };
        AuditReportRequest: {
            scope?: null | string;
            /** @default true */
            include_evidence: boolean;
            /** @default true */
            include_consensus: boolean;
            /** @default true */
            include_convergence: boolean;
            /** @default false */
            academic: boolean;
        };
        AuditReportResponse: {
            id: string;
            object: string;
            /** Format: int64 */
            created: number | string;
            scope: string;
            academic: boolean;
            include_evidence: boolean;
            include_consensus: boolean;
            include_convergence: boolean;
            report: components["schemas"]["SubstrateAuditReport"];
            billing: null | components["schemas"]["BillingReceipt"];
        };
        BestMoveRequest: {
            fen: string;
            /** Format: double */
            temperature: null | number | string;
            /** Format: int32 */
            depth: null | number | string;
            substrate: null | boolean;
        };
        BillingCatalogResponse: {
            object: string;
            data: components["schemas"]["CatalogServiceView"][];
        };
        BillingPlansResponse: {
            object: string;
            data: components["schemas"]["PlanView"][];
        };
        BillingPreflightRequest: {
            service_id: null | string;
            /** Format: int32 */
            units: number | string;
            tenant: null | string;
        };
        BillingProductsResponse: {
            object: string;
            data: components["schemas"]["ProductView"][];
        };
        BillingReceipt: {
            quote_id: string;
            /** Format: int64 */
            amount_cents: number | string;
            currency: string;
            tenant: string;
            service_id: string;
        };
        CapabilitiesResponse: {
            stream: string;
            endpoints: components["schemas"]["CapabilityEndpoints"];
        };
        CapabilityEndpoints: {
            chat_completions: components["schemas"]["CapabilityStatus"];
            completions: components["schemas"]["CapabilityStatus"];
            embeddings: components["schemas"]["CapabilityStatus"];
            audit_reports: components["schemas"]["CapabilityStatus"];
            visualizations: components["schemas"]["CapabilityStatus"];
            explainability_reports: components["schemas"]["CapabilityStatus"];
            billing: components["schemas"]["CapabilityStatus"];
            models: components["schemas"]["CapabilityStatus"];
        };
        CapabilityStatus: {
            status: string;
            backend?: null | string;
            billing?: null | string;
            reason?: null | string;
            provider?: null | string;
        };
        CatalogServiceView: {
            service_id: string;
            product_id: string;
            display_name: string;
            unit: string;
            /** Format: int64 */
            unit_price_cents: number | string;
            /** Format: int64 */
            base_fee_cents: number | string;
            currency: string;
            lookup_key: string;
            active: boolean;
            metered: boolean;
            recurring_interval: null | string;
            stripe_price_id: null | string;
        };
        CatalogSyncEntryView: {
            service_id: string;
            lookup_key: string;
            stripe_price_id: null | string;
            stripe_product_id: null | string;
            status: string;
        };
        CatalogSyncResponse: {
            stripe_configured: boolean;
            entries: components["schemas"]["CatalogSyncEntryView"][];
        };
        ChatChoice: {
            /** Format: int32 */
            index: number | string;
            message: components["schemas"]["ChatResponseMessage"];
            finish_reason: string;
        };
        ChatCompletionResponse: {
            id: string;
            object: string;
            /** Format: int64 */
            created: number | string;
            model: string;
            choices: components["schemas"]["ChatChoice"][];
            billing: null | components["schemas"]["BillingReceipt"];
            metadata: components["schemas"]["ChatMetadata"];
        };
        ChatCompletionsRequest: {
            model: null | string;
            messages: null | components["schemas"]["ChatMessage"][];
            /** @default false */
            stream: boolean;
            /** Format: int32 */
            max_tokens?: null | number | string;
            /** Format: int32 */
            max_completion_tokens?: null | number | string;
            /** Format: double */
            temperature?: null | number | string;
            /** Format: double */
            top_p?: null | number | string;
            /** Format: int32 */
            top_k?: null | number | string;
            /** Format: int32 */
            window?: null | number | string;
            /** Format: double */
            topic_boost?: null | number | string;
            stop?: unknown;
            /** @default false */
            web_search: boolean;
            /** Format: int32 */
            web_search_results?: null | number | string;
        };
        ChatMessage: {
            role: null | string;
            content: null | string;
        };
        ChatMetadata: {
            /** Format: int64 */
            witnesses?: null | number | string;
            /** Format: int32 */
            reply_rows?: null | number | string;
            /** Format: int32 */
            generated_tokens?: null | number | string;
            laplace?: null | components["schemas"]["LaplaceChatMetadata"];
        };
        ChatResponseMessage: {
            role: string;
            content: string;
        };
        CompletionChoice: {
            text: string;
            /** Format: int32 */
            index: number | string;
            finish_reason: null | string;
            logprobs: null | components["schemas"]["CompletionLogprobs"];
        };
        CompletionLogprobs: {
            token_logprobs: (number | string)[];
        };
        CompletionResponse: {
            id: string;
            object: string;
            /** Format: int64 */
            created: number | string;
            model: string;
            choices: components["schemas"]["CompletionChoice"][];
            billing: null | components["schemas"]["CompletionsReceipt"];
        };
        CompletionsReceipt: {
            quote_id: string;
            /** Format: int64 */
            amount_cents: number | string;
            currency: string;
            tenant: string;
        };
        CompletionsRequest: {
            model: null | string;
            prompt: null | string;
            /** @default false */
            stream: boolean;
            /** Format: int32 */
            max_tokens?: null | number | string;
            /** Format: double */
            temperature?: null | number | string;
            /** Format: double */
            top_p?: null | number | string;
            /** Format: int32 */
            top_k?: null | number | string;
            /** Format: int32 */
            window?: null | number | string;
            /** Format: double */
            topic_boost?: null | number | string;
            stop?: unknown;
            /** @default false */
            echo: boolean;
            /** Format: int32 */
            logprobs?: null | number | string;
        };
        ConsensusHealth: {
            /** Format: int64 */
            evidenceRows: number | string;
            /** Format: int64 */
            consensusRows: number | string;
            /** Format: double */
            dedupRatio: null | number | string;
            /** Format: double */
            avgWitnesses: null | number | string;
            /** Format: int64 */
            maxWitnesses: null | number | string;
        };
        CreditConsumeRequest: {
            tenant: null | string;
            service_id: null | string;
            /**
             * Format: int32
             * @default 1
             */
            units: number | string;
        };
        CreditConsumeResponse: {
            accepted: boolean;
            tenant: string;
            plan_id: string;
            service_id: string;
            /** Format: int32 */
            units: number | string;
            /** Format: int32 */
            remaining: number | string;
            /** Format: date-time */
            period_end: string;
            status: string;
        };
        EmbeddingData: {
            object: string;
            /** Format: int32 */
            index: number | string;
            embedding: (number | string)[];
            laplace: components["schemas"]["EmbeddingProvenance"];
        };
        EmbeddingFormView: {
            /** Format: double */
            x: number | string;
            /** Format: double */
            y: number | string;
            /** Format: double */
            z: number | string;
            /** Format: double */
            m: number | string;
            /** Format: double */
            radius: number | string;
            /** Format: int32 */
            constituents: number | string;
        };
        EmbeddingProvenance: {
            input: string;
            resolved: boolean;
            entity_id: null | string;
            form: null | components["schemas"]["EmbeddingFormView"];
            meaning: null | components["schemas"]["MeaningNeighborView"][];
        };
        EmbeddingsRequest: {
            model: null | string;
            input: null | components["schemas"]["JsonElement"];
        };
        EmbeddingsResponse: {
            object: string;
            data: components["schemas"]["EmbeddingData"][];
            model: string;
            usage: components["schemas"]["EmbeddingsUsage"];
        };
        EmbeddingsUsage: {
            /** Format: int32 */
            prompt_tokens: number | string;
            /** Format: int32 */
            total_tokens: number | string;
        };
        EntitlementsResponse: {
            tenant: string;
            data: components["schemas"]["EntitlementView"][];
        };
        EntitlementView: {
            tenant: string;
            plan_id: string;
            status: string;
            /** Format: date-time */
            period_start: string;
            /** Format: date-time */
            period_end: string;
            monthly_credits: {
                [key: string]: number | string;
            };
            used_credits: {
                [key: string]: number | string;
            };
            stripe_customer_id: null | string;
            stripe_subscription_id: null | string;
            /** Format: date-time */
            updated_at: string;
        };
        ErrorBody: {
            type: string;
            code: string;
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        EvidenceResponse: {
            entity_id: string;
            entity_label: string;
            evidence: components["schemas"]["LabeledEvidenceItem"][];
        };
        EvidenceSample: {
            typeIdHex: string;
            objectIdHex: string;
            sourceIdHex: string;
            contextIdHex: null | string;
            /** Format: int16 */
            outcome: number | string;
            /** Format: int64 */
            observationCount: number | string;
        };
        ExecuteHeader: {
            name: string;
            value: string;
        };
        ExplainQuoteRequest: {
            tenant: null | string;
            prompt: null | string;
            /** Format: int32 */
            depth: number | string;
            /** Format: int32 */
            beam: number | string;
            /** @default false */
            academic: boolean;
        };
        ExplainQuoteResponse: {
            quote_id: string;
            tenant: string;
            service_id: string;
            /** Format: int32 */
            depth: number | string;
            /** Format: int32 */
            beam: number | string;
            academic: boolean;
            /** Format: int64 */
            estimated_trace_nodes: number | string;
            /** Format: int32 */
            billable_units: number | string;
            unit: string;
            /** Format: int64 */
            amount_cents: number | string;
            currency: string;
            status: string;
            /** Format: date-time */
            expires_at: string;
            stripe_checkout_url: null | string;
            next: components["schemas"]["QuoteNextStep"];
        };
        ExplainReportRequest: {
            prompt: null | string;
            /** Format: int32 */
            depth: number | string;
            /** Format: int32 */
            beam: number | string;
            /** @default false */
            academic: boolean;
        };
        ExplainReportResponse: {
            id: string;
            object: string;
            /** Format: int64 */
            created: number | string;
            prompt: string;
            /** Format: int32 */
            depth: number | string;
            /** Format: int32 */
            beam: number | string;
            academic: boolean;
            trace: components["schemas"]["ExplainTraceStep"][];
            billing: null | components["schemas"]["BillingReceipt"];
        };
        ExplainTraceStep: {
            /** Format: int32 */
            depth: number | string;
            pathHex: string[];
            typePathHex: string[];
            entityIdHex: string;
            entityLabel: string;
            /** Format: double */
            effectiveMu: number | string;
            /** Format: double */
            pathMu: number | string;
            /** Format: int64 */
            witnesses: number | string;
            evidence: components["schemas"]["EvidenceSample"][];
        };
        FenRequest: {
            fen: string;
        };
        HealthResponse: {
            status: string;
            stream: string;
        };
        JsonElement: unknown;
        LabeledEvidenceItem: {
            type_id: string;
            type_label: string;
            object_id: string;
            object_label: string;
            source_id: string;
            source_label: string;
            context_id: null | string;
            /** Format: int16 */
            outcome: number | string;
            /** Format: int64 */
            observation_count: number | string;
        };
        LabStartRequest: {
            kind: null | string;
            config: null | Record<string, never>;
        };
        LaplaceChatMetadata: {
            provenance: components["schemas"]["ProvenanceLine"][];
        };
        MeaningNeighborView: {
            relation: string;
            object: string;
            /** Format: double */
            eff_mu: number | string;
            /** Format: int64 */
            witnesses: number | string;
        };
        ModelInfo: {
            id: string;
            object: string;
            /** Format: int64 */
            created: number | string;
            owned_by: string;
            status?: null | string;
        };
        ModelList: {
            object: string;
            data: components["schemas"]["ModelInfo"][];
        };
        MoveRequest: {
            fen: string;
            uci: string;
        };
        PaymentRequiredBody: {
            type: string;
            code: string;
            message: string;
            detail: unknown;
        };
        PaymentRequiredResponse: {
            error: components["schemas"]["PaymentRequiredBody"];
        };
        PlanNextStep: {
            checkout_url: null | string;
            note: string;
        };
        PlanSubscribeRequest: {
            tenant: null | string;
        };
        PlanSubscribeResponse: {
            quote_id: string;
            tenant: string;
            plan_id: string;
            service_id: string;
            /** Format: int64 */
            monthly_price_cents: number | string;
            /** Format: int64 */
            amount_cents: number | string;
            currency: string;
            status: string;
            stripe_checkout_url: null | string;
            monthly_credits: {
                [key: string]: number | string;
            };
            next: components["schemas"]["PlanNextStep"];
        };
        PlanView: {
            plan_id: string;
            service_id: string;
            name: string;
            description: string;
            /** Format: int64 */
            monthly_price_cents: number | string;
            currency: string;
            monthly_credits: {
                [key: string]: number | string;
            };
            included_product_ids: string[];
            support_tier: string;
            active: boolean;
        };
        PreflightQuoteResponse: {
            quote_id: string;
            tenant: string;
            service_id: string;
            /** Format: int32 */
            units: number | string;
            /** Format: int64 */
            amount_cents: number | string;
            currency: string;
            status: string;
            /** Format: date-time */
            expires_at: string;
            stripe_checkout_url: null | string;
            next: components["schemas"]["QuoteNextStep"];
        };
        ProductPriceView: {
            service_id: string;
            unit: string;
            /** Format: int64 */
            unit_price_cents: number | string;
            /** Format: int64 */
            base_fee_cents: number | string;
            currency: string;
            lookup_key: string;
            metered: boolean;
            recurring_interval: null | string;
        };
        ProductView: {
            product_id: string;
            name: string;
            description: string;
            category: string;
            prices: components["schemas"]["ProductPriceView"][];
        };
        ProvenanceLine: {
            reply: string;
            /** Format: double */
            eff_mu: number | string;
            /** Format: int64 */
            witnesses: number | string;
        };
        QuoteNextStep: {
            execute_header: components["schemas"]["ExecuteHeader"];
            note: string;
        };
        QuoteStatusResponse: {
            quote_id: string;
            tenant: string;
            service_id: string;
            /** Format: int32 */
            units: number | string;
            /** Format: int64 */
            amount_cents: number | string;
            currency: string;
            status: string;
            consumed: boolean;
            stripe_checkout_url: null | string;
            /** Format: date-time */
            expires_at: string;
        };
        ReadinessResponse: {
            ready: boolean;
            substrate_reachable: boolean;
            /** Format: int64 */
            entities: number | string;
            /** Format: int64 */
            consensus_relations: number | string;
            perfcache_ready: boolean;
            detail?: null | string;
        };
        RecipeQuoteRequest: {
            tenant: null | string;
            action: null | string;
            /**
             * Format: int32
             * @default 1
             */
            content_items: number | string;
            /** @default false */
            commercial: boolean;
            /** @default false */
            private_export: boolean;
        };
        RecipeQuoteResponse: {
            quote_id: string;
            tenant: string;
            service_id: string;
            action: string;
            /** Format: int32 */
            content_items: number | string;
            commercial: boolean;
            private_export: boolean;
            /** Format: int64 */
            metered_items: number | string;
            /** Format: int32 */
            billable_units: number | string;
            unit: string;
            /** Format: int64 */
            items_per_unit: number | string;
            /** Format: int64 */
            amount_cents: number | string;
            currency: string;
            status: string;
            /** Format: date-time */
            expires_at: string;
            stripe_checkout_url: null | string;
            next: components["schemas"]["QuoteNextStep"];
        };
        SubstrateAuditReport: {
            counts: components["schemas"]["SubstrateCount"][];
            consensus: null | components["schemas"]["ConsensusHealth"];
            /** Format: int64 */
            multiSourceEntityCount: null | number | string;
            topRelations: components["schemas"]["VisualizationEdge"][];
        };
        SubstrateCount: {
            metric: string;
            /** Format: int64 */
            value: number | string;
        };
        SubstrateVisualizationGraph: {
            nodes: components["schemas"]["VisualizationNode"][];
            edges: components["schemas"]["VisualizationEdge"][];
        };
        SynthesisQuoteRequest: {
            tenant: null | string;
            /** Format: int64 */
            vocab_size: number | string;
            /** Format: int64 */
            hidden_size: number | string;
            /** Format: int32 */
            num_layers: number | string;
            /** Format: int32 */
            num_heads: number | string;
            /** Format: int32 */
            num_kv_heads?: null | number | string;
            /**
             * Format: int64
             * @default 0
             */
            intermediate_size: number | string;
            /** @default false */
            tied_embeddings: boolean;
            format?: null | string;
        };
        SynthesisQuoteResponse: {
            quote_id: string;
            tenant: string;
            service_id: string;
            /** Format: int64 */
            estimated_parameters: number | string;
            /** Format: int32 */
            billable_units: number | string;
            unit: string;
            /** Format: int64 */
            amount_cents: number | string;
            currency: string;
            status: string;
            /** Format: date-time */
            expires_at: string;
            stripe_checkout_url: null | string;
            format: string;
            next: components["schemas"]["QuoteNextStep"];
        };
        UsageEntry: {
            quoteId: string;
            tenant: string;
            serviceId: string;
            /** Format: int32 */
            units: number | string;
            /** Format: int64 */
            amountCents: number | string;
            /** Format: date-time */
            executedAt: string;
        };
        UsageResponse: {
            tenant: string;
            /** Format: int64 */
            total_amount_cents: number | string;
            entries: components["schemas"]["UsageEntry"][];
        };
        VisualizationEdge: {
            subjectIdHex: string;
            subject: string;
            typeIdHex: string;
            type: string;
            objectIdHex: string;
            object: string;
            /** Format: double */
            effectiveMu: number | string;
            /** Format: int64 */
            witnesses: number | string;
        };
        VisualizationExecuteRequest: {
            /** Format: int32 */
            limit?: null | number | string;
            /** @default true */
            include_geometry: boolean;
            /** @default false */
            include_evidence: boolean;
            format?: null | string;
        };
        VisualizationGraphResponse: {
            id: string;
            object: string;
            /** Format: int64 */
            created: number | string;
            format: string;
            include_geometry: boolean;
            include_evidence: boolean;
            graph: components["schemas"]["SubstrateVisualizationGraph"];
            billing: null | components["schemas"]["BillingReceipt"];
        };
        VisualizationNode: {
            idHex: string;
            label: string;
            /** Format: double */
            x: null | number | string;
            /** Format: double */
            y: null | number | string;
            /** Format: double */
            z: null | number | string;
            /** Format: double */
            m: null | number | string;
            /** Format: double */
            radius: null | number | string;
            /** Format: int32 */
            constituents: null | number | string;
            /** Format: int64 */
            evidenceRows: null | number | string;
        };
        VisualizationQuoteRequest: {
            tenant: null | string;
            /** Format: int32 */
            nodes: number | string;
            /**
             * Format: int32
             * @default 0
             */
            edges: number | string;
            /** @default true */
            include_geometry: boolean;
            /** @default false */
            include_evidence: boolean;
            /** @default false */
            interactive: boolean;
            format?: null | string;
        };
        VisualizationQuoteResponse: {
            quote_id: string;
            tenant: string;
            service_id: string;
            /** Format: int32 */
            nodes: number | string;
            /** Format: int32 */
            edges: number | string;
            include_geometry: boolean;
            include_evidence: boolean;
            interactive: boolean;
            format: string;
            /** Format: int64 */
            metered_items: number | string;
            /** Format: int32 */
            billable_units: number | string;
            unit: string;
            /** Format: int64 */
            items_per_unit: number | string;
            /** Format: int64 */
            amount_cents: number | string;
            currency: string;
            status: string;
            /** Format: date-time */
            expires_at: string;
            stripe_checkout_url: null | string;
            next: components["schemas"]["QuoteNextStep"];
        };
        WebhookResponse: {
            accepted: boolean;
            verified: boolean;
            duplicate: boolean;
            event_id: null | string;
            event_type: null | string;
            status: string;
            tenant: null | string;
            service_id: null | string;
            quote_id: null | string;
            plan_id: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
