import { useNavigate } from 'react-router-dom';
import { Muted } from '@ui';
import { useAppStore, type QuerySeed } from '../store';
import { Leaderboards } from './Leaderboards';
import { Scoreboard } from './Scoreboard';
import styles from './HomeView.module.css';

/** Where a mode card or example sends the user. */
export type HomeTarget = 'chat' | 'query';

interface Props {
  /** Switch the main shell to a sibling tab (chat/query live in MainShell state). */
  onGoto: (target: HomeTarget) => void;
}

/**
 * The landing. It answers the two questions a first visit actually has — "what
 * is this?" and "what can I do with it?" — before offering any input box.
 *
 * "What is this" is answered by the live scoreboard: the size of the
 * witnessed graph and whether a source is folding right now. "What can I do" is the three modes, named for the
 * distinct thing each one does, plus concrete example reads that deep-link into
 * the Query console already set up. Nothing here is decorative — every number
 * and every mode is a real capability of the substrate underneath.
 */
export function HomeView({ onGoto }: Props) {
  const nav = useNavigate();
  const setQuerySeed = useAppStore((s) => s.setQuerySeed);

  const runExample = (seed: QuerySeed) => {
    // Two-topic comparisons have a home of their own — the matchup page.
    if (seed.topic2 && (seed.shape === 'reason' || seed.shape === 'is_a')) {
      nav(`/explore/matchup/${encodeURIComponent(seed.topic)}/${encodeURIComponent(seed.topic2)}`);
      return;
    }
    // Shaped reads still seed the console; a bare topic goes to the topic page,
    // which shows every read at once instead of making you pick one.
    if (!seed.shape || seed.shape === 'describe' || seed.shape === 'band_facts' || seed.shape === 'define') {
      nav(`/topic/${encodeURIComponent(seed.topic)}`);
      return;
    }
    setQuerySeed(seed);
    onGoto('query');
  };

  return (
    <div className={styles.home}>
      {/* section + h2, not header + h1: the page's sole h1 and header landmark
          belong to the app shell — doubling them broke the heading outline. */}
      <section className={styles.hero}>
        <h2 className={styles.title}>The substrate remembers what it was told, and who told it.</h2>
        <p className={styles.lede}>
          Laplace stores meaning as a rated graph of witnessed evidence — not weights. Every fact
          carries who asserted it and how strongly the whole graph agrees. Ask it, and the answer
          comes back with its confidence and its witnesses attached.
        </p>
      </section>

      <Scoreboard />

      <Leaderboards />

      <section className={styles.modes} aria-label="What you can do">
        <ModeCard
          name="Chat"
          tagline="Converse with the graph."
          body="Ask in plain language. Every reply is read from witnessed consensus and shows the μ and witness count behind it — or, if you prefer, is generated by walking the trajectory graph."
          cta="Start a conversation"
          onClick={() => onGoto('chat')}
        />
        <ModeCard
          name="Query"
          tagline="Ask structurally."
          body="Name a topic, choose the shape of read, and narrow it with the salience-band lens. Turn the dials — depth, breadth, spread, seed. No natural-language guessing; the question is the shape you pick."
          cta="Open the console"
          accent
          onClick={() => onGoto('query')}
        />
        <ModeCard
          name="Explore"
          tagline="Walk the warehouse."
          body="Browse every entity, its evidence, its geometry on the sphere, and the consensus web around it. Follow provenance down to the individual witness, and export any neighborhood."
          cta="Enter the warehouse"
          onClick={() => nav('/explore')}
        />
      </section>

      <section className={styles.examples} aria-label="Things you can ask">
        <div className={styles.examplesHead}>
          <span className={styles.examplesTitle}>Try a structural read</span>
          <Muted className={styles.examplesSub}>each opens the Query console, set up and ready to run</Muted>
        </div>
        <div className={styles.exampleGrid}>
          {EXAMPLES.map((ex) => (
            <button key={ex.label} type="button" className={styles.example} onClick={() => runExample(ex.seed)}>
              <span className={styles.exampleShape}>{ex.seed.shape ?? 'describe'}</span>
              <span className={styles.exampleLabel}>{ex.label}</span>
            </button>
          ))}
        </div>
      </section>
    </div>
  );
}


function ModeCard({
  name, tagline, body, cta, accent, onClick,
}: {
  name: string; tagline: string; body: string; cta: string; accent?: boolean; onClick: () => void;
}) {
  return (
    <button type="button" className={`${styles.mode} ${accent ? styles.modeAccent : ''}`} onClick={onClick}>
      <span className={styles.modeName}>{name}</span>
      <span className={styles.modeTagline}>{tagline}</span>
      <span className={styles.modeBody}>{body}</span>
      <span className={styles.modeCta}>{cta} →</span>
    </button>
  );
}

const EXAMPLES: { label: string; seed: QuerySeed }[] = [
  { label: 'What does "entropy" mean?', seed: { topic: 'entropy', shape: 'define' } },
  { label: 'Parts of a "cell"', seed: { topic: 'cell', shape: 'related', relationType: 'HAS_PART' } },
  { label: 'How do "dog" and "wolf" relate?', seed: { topic: 'dog', topic2: 'wolf', shape: 'reason' } },
  { label: 'Is a "whale" a "mammal"?', seed: { topic: 'whale', topic2: 'mammal', shape: 'is_a' } },
  { label: 'Everything witnessed about "gravity"', seed: { topic: 'gravity', shape: 'band_facts' } },
  { label: '"water" across languages', seed: { topic: 'water', shape: 'languages' } },
];
