# Helpers for manifest.install / manifest.upgrade → generated #include chains.

function(laplace_write_sql_chain chain_file manifest_file src_sql_dir)
    if(NOT EXISTS "${manifest_file}")
        message(FATAL_ERROR "SQL manifest not found: ${manifest_file}")
    endif()
    file(STRINGS "${manifest_file}" _lines)
    set(_chain "")
    set(_deps "")
    set(_hash [[#]])
    foreach(_line IN LISTS _lines)
        string(STRIP "${_line}" _line)
        if(_line STREQUAL "")
            continue()
        endif()
        string(FIND "${_line}" "${_hash}" _hash_pos)
        if(_hash_pos EQUAL 0)
            continue()
        endif()
        string(APPEND _chain "#include \"${_line}\"\n")
        list(APPEND _deps "${src_sql_dir}/${_line}")
    endforeach()
    file(WRITE "${chain_file}" "${_chain}")
    set(SQL_CHAIN_DEPS "${_deps}" PARENT_SCOPE)
endfunction()