#pragma once

/* Generated from engine/manifest/relation_types.toml — do not edit. */

#define LAPLACE_HIGHWAY_MAGIC    0x5957484Cu
#define LAPLACE_HIGHWAY_VERSION  1u
#define LAPLACE_HIGHWAY_REL_COUNT   179u
#define LAPLACE_HIGHWAY_BAND_COUNT  13u
#define HIGHWAY_BUCKET_SIZE         1024u
#define HIGHWAY_BUCKET_MASK         1023u

/* Bit position of each relation type in the 256-bit highway mask */
#define HIGHWAY_BIT_ADJACENT_TO_PIXEL                                  0u
#define HIGHWAY_BIT_ALSO_SEE                                           1u
#define HIGHWAY_BIT_ATTENDS                                            2u
#define HIGHWAY_BIT_AT_LOCATION                                        3u
#define HIGHWAY_BIT_BORROWED_FROM                                      4u
#define HIGHWAY_BIT_CALLS                                              5u
#define HIGHWAY_BIT_CANONICAL_DECOMPOSES_TO                            6u
#define HIGHWAY_BIT_CAPABLE_OF                                         7u
#define HIGHWAY_BIT_CAPTIONS                                           8u
#define HIGHWAY_BIT_CAUSATIVE_OF                                       9u
#define HIGHWAY_BIT_CAUSES                                             10u
#define HIGHWAY_BIT_CAUSES_DESIRE                                      11u
#define HIGHWAY_BIT_COMPATIBILITY_DECOMPOSES_TO                        12u
#define HIGHWAY_BIT_COMPLETES_TO                                       13u
#define HIGHWAY_BIT_CONFUSABLE_WITH                                    14u
#define HIGHWAY_BIT_CONTAINS                                           15u
#define HIGHWAY_BIT_CONTINUES_TO                                       16u
#define HIGHWAY_BIT_CORRESPONDS_TO                                     17u
#define HIGHWAY_BIT_CREATED_BY                                         18u
#define HIGHWAY_BIT_DECODES_TO                                         19u
#define HIGHWAY_BIT_DEPENDS_ON                                         20u
#define HIGHWAY_BIT_DEPICTS                                            21u
#define HIGHWAY_BIT_DERIVATIONALLY_RELATED                             22u
#define HIGHWAY_BIT_DERIVED_FROM                                       23u
#define HIGHWAY_BIT_DESIRES                                            24u
#define HIGHWAY_BIT_DISTINCT_FROM                                      25u
#define HIGHWAY_BIT_ENHANCED_DEPENDS_ON                                26u
#define HIGHWAY_BIT_ENTAILS                                            27u
#define HIGHWAY_BIT_ETYMOLOGICALLY_DERIVED_FROM                        28u
#define HIGHWAY_BIT_ETYMOLOGICALLY_RELATED_TO                          29u
#define HIGHWAY_BIT_EVOKES_FRAME                                       30u
#define HIGHWAY_BIT_EXCLUDES                                           31u
#define HIGHWAY_BIT_EXPLAINS                                           32u
#define HIGHWAY_BIT_FORM_OF                                            33u
#define HIGHWAY_BIT_FRAME_USES                                         34u
#define HIGHWAY_BIT_GAME_AT                                            35u
#define HIGHWAY_BIT_GAME_AT_PLY                                        36u
#define HIGHWAY_BIT_GAME_HAS_ECO                                       37u
#define HIGHWAY_BIT_GAME_HAS_MOTIF                                     38u
#define HIGHWAY_BIT_GAME_HAS_OPENING                                   39u
#define HIGHWAY_BIT_HAS_A                                              40u
#define HIGHWAY_BIT_HAS_AGE                                            41u
#define HIGHWAY_BIT_HAS_ATTRIBUTE                                      42u
#define HIGHWAY_BIT_HAS_BIDI_CLASS                                     43u
#define HIGHWAY_BIT_HAS_BLACK                                          44u
#define HIGHWAY_BIT_HAS_BLOCK                                          45u
#define HIGHWAY_BIT_HAS_CLOCK                                          46u
#define HIGHWAY_BIT_HAS_COMBINING_CLASS                                47u
#define HIGHWAY_BIT_HAS_CONTEXT                                        48u
#define HIGHWAY_BIT_HAS_DBPEDIA_RELATION                               49u
#define HIGHWAY_BIT_HAS_DEFINITION                                     50u
#define HIGHWAY_BIT_HAS_DOMAIN_REGION                                  51u
#define HIGHWAY_BIT_HAS_DOMAIN_TOPIC                                   52u
#define HIGHWAY_BIT_HAS_DOMAIN_USAGE                                   53u
#define HIGHWAY_BIT_HAS_EAST_ASIAN_WIDTH                               54u
#define HIGHWAY_BIT_HAS_ECO                                            55u
#define HIGHWAY_BIT_HAS_EMOJI_PROPERTY                                 56u
#define HIGHWAY_BIT_HAS_ETYMOLOGY                                      57u
#define HIGHWAY_BIT_HAS_EVAL                                           58u
#define HIGHWAY_BIT_HAS_EVAL_TOKEN                                     59u
#define HIGHWAY_BIT_HAS_EVENT                                          60u
#define HIGHWAY_BIT_HAS_EXAMPLE                                        61u
#define HIGHWAY_BIT_HAS_EXTERNAL_ID                                    62u
#define HIGHWAY_BIT_HAS_FEATURE                                        63u
#define HIGHWAY_BIT_HAS_FIRST_SUBEVENT                                 64u
#define HIGHWAY_BIT_HAS_FRAME_ELEMENT                                  65u
#define HIGHWAY_BIT_HAS_GENERAL_CATEGORY                               66u
#define HIGHWAY_BIT_HAS_ISO639_1_CODE                                  67u
#define HIGHWAY_BIT_HAS_ISO639_2B_CODE                                 68u
#define HIGHWAY_BIT_HAS_ISO639_2T_CODE                                 69u
#define HIGHWAY_BIT_HAS_ISO639_2_CODE                                  70u
#define HIGHWAY_BIT_HAS_JOINING_TYPE                                   71u
#define HIGHWAY_BIT_HAS_LANGUAGE                                       72u
#define HIGHWAY_BIT_HAS_LANGUAGE_SCOPE                                 73u
#define HIGHWAY_BIT_HAS_LANGUAGE_TYPE                                  74u
#define HIGHWAY_BIT_HAS_LAST_SUBEVENT                                  75u
#define HIGHWAY_BIT_HAS_LEX_CATEGORY                                   76u
#define HIGHWAY_BIT_HAS_LINE_BREAK                                     77u
#define HIGHWAY_BIT_HAS_LOWERCASE_MAPPING                              78u
#define HIGHWAY_BIT_HAS_MEMBER                                         79u
#define HIGHWAY_BIT_HAS_MIRROR                                         80u
#define HIGHWAY_BIT_HAS_NAME                                           81u
#define HIGHWAY_BIT_HAS_NAME_ALIAS                                     82u
#define HIGHWAY_BIT_HAS_NUMERIC_TYPE                                   83u
#define HIGHWAY_BIT_HAS_NUMERIC_VALUE                                  84u
#define HIGHWAY_BIT_HAS_PART                                           85u
#define HIGHWAY_BIT_HAS_POS                                            86u
#define HIGHWAY_BIT_HAS_PREREQUISITE                                   87u
#define HIGHWAY_BIT_HAS_PROPERTY                                       88u
#define HIGHWAY_BIT_HAS_RATING                                         89u
#define HIGHWAY_BIT_HAS_RESULT                                         90u
#define HIGHWAY_BIT_HAS_SCRIPT                                         91u
#define HIGHWAY_BIT_HAS_SEMANTIC_ROLE                                  92u
#define HIGHWAY_BIT_HAS_SENSE                                          93u
#define HIGHWAY_BIT_HAS_SUBEVENT                                       94u
#define HIGHWAY_BIT_HAS_SUBSTANCE                                      95u
#define HIGHWAY_BIT_HAS_SYNSET_KEY                                     96u
#define HIGHWAY_BIT_HAS_TC_CLASS                                       97u
#define HIGHWAY_BIT_HAS_TERMINATION                                    98u
#define HIGHWAY_BIT_HAS_THEMATIC_ROLE                                  99u
#define HIGHWAY_BIT_HAS_THINK_CLASS                                    100u
#define HIGHWAY_BIT_HAS_TIME_CONTROL                                   101u
#define HIGHWAY_BIT_HAS_TITLECASE_MAPPING                              102u
#define HIGHWAY_BIT_HAS_UPPERCASE_MAPPING                              103u
#define HIGHWAY_BIT_HAS_USAGE_REGISTER                                 104u
#define HIGHWAY_BIT_HAS_UTF8_ROLE                                      105u
#define HIGHWAY_BIT_HAS_VALENCE_PATTERN                                106u
#define HIGHWAY_BIT_HAS_VARIANT_OF                                     107u
#define HIGHWAY_BIT_HAS_VERB_FRAME                                     108u
#define HIGHWAY_BIT_HAS_WHITE                                          109u
#define HIGHWAY_BIT_HAS_XPOS                                           110u
#define HIGHWAY_BIT_INCHOATIVE_OF                                      111u
#define HIGHWAY_BIT_INHERITED_FROM                                     112u
#define HIGHWAY_BIT_INHERITS_FROM                                      113u
#define HIGHWAY_BIT_IN_VERB_GROUP_WITH                                 114u
#define HIGHWAY_BIT_IS_A                                               115u
#define HIGHWAY_BIT_IS_AFTER                                           116u
#define HIGHWAY_BIT_IS_ANTONYM_OF                                      117u
#define HIGHWAY_BIT_IS_AT_SAMPLE                                       118u
#define HIGHWAY_BIT_IS_BEFORE                                          119u
#define HIGHWAY_BIT_IS_COORDINATE_TERM_WITH                            120u
#define HIGHWAY_BIT_IS_EXAMPLE_OF                                      121u
#define HIGHWAY_BIT_IS_INSTANCE_OF                                     122u
#define HIGHWAY_BIT_IS_LANGUAGE_CODE                                   123u
#define HIGHWAY_BIT_IS_LEMMA_OF                                        124u
#define HIGHWAY_BIT_IS_PARTICIPLE_OF                                   125u
#define HIGHWAY_BIT_IS_PIXEL_OF                                        126u
#define HIGHWAY_BIT_IS_SENSE_OF                                        127u
#define HIGHWAY_BIT_IS_SIMILAR_TO                                      128u
#define HIGHWAY_BIT_IS_SYNONYM_OF                                      129u
#define HIGHWAY_BIT_IS_TRANSLATION_OF                                  130u
#define HIGHWAY_BIT_IS_TYPED_AS                                        131u
#define HIGHWAY_BIT_LOCATED_NEAR                                       132u
#define HIGHWAY_BIT_MADE_UP_OF                                         133u
#define HIGHWAY_BIT_MANNER_OF                                          134u
#define HIGHWAY_BIT_MEMBER_OF_MACROLANGUAGE                            135u
#define HIGHWAY_BIT_MEMBER_OF_VERBNET_CLASS                            136u
#define HIGHWAY_BIT_MERGES_WITH                                        137u
#define HIGHWAY_BIT_MOTIVATED_BY_GOAL                                  138u
#define HIGHWAY_BIT_MOVE                                               139u
#define HIGHWAY_BIT_MOVE_QUALITY                                       140u
#define HIGHWAY_BIT_NORMALIZES_TO                                      141u
#define HIGHWAY_BIT_NOT_CAPABLE_OF                                     142u
#define HIGHWAY_BIT_NOT_DESIRES                                        143u
#define HIGHWAY_BIT_NOT_HAS_PROPERTY                                   144u
#define HIGHWAY_BIT_NOT_USED_FOR                                       145u
#define HIGHWAY_BIT_OBJECT_USE                                         146u
#define HIGHWAY_BIT_OBSTRUCTED_BY                                      147u
#define HIGHWAY_BIT_ON_DATE                                            148u
#define HIGHWAY_BIT_OPENING_NAME                                       149u
#define HIGHWAY_BIT_OUTCOME                                            150u
#define HIGHWAY_BIT_OV_RELATES                                         151u
#define HIGHWAY_BIT_O_EFFECT                                           152u
#define HIGHWAY_BIT_O_REACT                                            153u
#define HIGHWAY_BIT_O_WANT                                             154u
#define HIGHWAY_BIT_PERSPECTIVE_ON                                     155u
#define HIGHWAY_BIT_PERTAINS_TO                                        156u
#define HIGHWAY_BIT_PLAYED_BY                                          157u
#define HIGHWAY_BIT_PRECEDES                                           158u
#define HIGHWAY_BIT_RECEIVES_ACTION                                    159u
#define HIGHWAY_BIT_REFERENCES                                         160u
#define HIGHWAY_BIT_RELATED_TO                                         161u
#define HIGHWAY_BIT_REQUIRES                                           162u
#define HIGHWAY_BIT_ROLE_CORRESPONDS_TO                                163u
#define HIGHWAY_BIT_SUPERSEDED_BY                                      164u
#define HIGHWAY_BIT_SYMBOL_OF                                          165u
#define HIGHWAY_BIT_TOKEN_MAPS_TO                                      166u
#define HIGHWAY_BIT_TRANSCRIBES_AS                                     167u
#define HIGHWAY_BIT_USED_FOR                                           168u
#define HIGHWAY_BIT_USES_SCRIPT                                        169u
#define HIGHWAY_BIT_USES_SCRIPT_EXTENSION                              170u
#define HIGHWAY_BIT_X_ATTR                                             171u
#define HIGHWAY_BIT_X_EFFECT                                           172u
#define HIGHWAY_BIT_X_FILLED_BY                                        173u
#define HIGHWAY_BIT_X_INTENT                                           174u
#define HIGHWAY_BIT_X_NEED                                             175u
#define HIGHWAY_BIT_X_REACT                                            176u
#define HIGHWAY_BIT_X_REASON                                           177u
#define HIGHWAY_BIT_X_WANT                                             178u

/* Band index constants */
#define HIGHWAY_BAND_MANDATE                                       0u
#define HIGHWAY_BAND_DEFINITIONAL                                  1u
#define HIGHWAY_BAND_TAXONOMIC                                     2u
#define HIGHWAY_BAND_EQUIVALENCE                                   3u
#define HIGHWAY_BAND_PARTITIVE                                     4u
#define HIGHWAY_BAND_CAUSAL                                        5u
#define HIGHWAY_BAND_OPPOSITIONAL                                  6u
#define HIGHWAY_BAND_ASSOCIATIVE                                   7u
#define HIGHWAY_BAND_TENSOR_CALCULATION                            8u
#define HIGHWAY_BAND_LEXICAL_GLUE                                  9u
#define HIGHWAY_BAND_SCALAR_VALUED                                 10u
#define HIGHWAY_BAND_STANDARDS_STRUCTURAL                          11u
#define HIGHWAY_BAND_PROBATIONARY                                  12u
