#pragma once

/* Generated from engine/manifest/relation_types.toml — do not edit. */

#define LAPLACE_HIGHWAY_MAGIC    0x5957484Cu
#define LAPLACE_HIGHWAY_VERSION  1u
#define LAPLACE_HIGHWAY_REL_COUNT   203u
#define LAPLACE_HIGHWAY_BAND_COUNT  13u
#define HIGHWAY_BUCKET_SIZE         1024u
#define HIGHWAY_BUCKET_MASK         1023u

/* Bit position of each relation type in the 256-bit highway mask */
#define HIGHWAY_BIT_ADJACENT_TO_PIXEL                                  0u
#define HIGHWAY_BIT_ALSO_SEE                                           1u
#define HIGHWAY_BIT_APPEARS_IN                                         2u
#define HIGHWAY_BIT_ATTENDS                                            3u
#define HIGHWAY_BIT_AT_LOCATION                                        4u
#define HIGHWAY_BIT_BORROWED_FROM                                      5u
#define HIGHWAY_BIT_CALLS                                              6u
#define HIGHWAY_BIT_CANONICAL_DECOMPOSES_TO                            7u
#define HIGHWAY_BIT_CAPABLE_OF                                         8u
#define HIGHWAY_BIT_CAPTIONS                                           9u
#define HIGHWAY_BIT_CAUSATIVE_OF                                       10u
#define HIGHWAY_BIT_CAUSES                                             11u
#define HIGHWAY_BIT_CAUSES_DESIRE                                      12u
#define HIGHWAY_BIT_COMPATIBILITY_DECOMPOSES_TO                        13u
#define HIGHWAY_BIT_COMPLETES_TO                                       14u
#define HIGHWAY_BIT_CONFUSABLE_WITH                                    15u
#define HIGHWAY_BIT_CONTAINS                                           16u
#define HIGHWAY_BIT_CONTINUES_TO                                       17u
#define HIGHWAY_BIT_CORRESPONDS_TO                                     18u
#define HIGHWAY_BIT_CREATED_BY                                         19u
#define HIGHWAY_BIT_DECODES_TO                                         20u
#define HIGHWAY_BIT_DEPENDS_ON                                         21u
#define HIGHWAY_BIT_DEPICTS                                            22u
#define HIGHWAY_BIT_DERIVATIONALLY_RELATED                             23u
#define HIGHWAY_BIT_DERIVED_FROM                                       24u
#define HIGHWAY_BIT_DESIRES                                            25u
#define HIGHWAY_BIT_DISTINCT_FROM                                      26u
#define HIGHWAY_BIT_ENCODES                                            27u
#define HIGHWAY_BIT_ENHANCED_DEPENDS_ON                                28u
#define HIGHWAY_BIT_ENTAILS                                            29u
#define HIGHWAY_BIT_ETYMOLOGICALLY_DERIVED_FROM                        30u
#define HIGHWAY_BIT_ETYMOLOGICALLY_RELATED_TO                          31u
#define HIGHWAY_BIT_EVOKES_FRAME                                       32u
#define HIGHWAY_BIT_EXCLUDES                                           33u
#define HIGHWAY_BIT_EXPLAINS                                           34u
#define HIGHWAY_BIT_FORM_OF                                            35u
#define HIGHWAY_BIT_FRAME_USES                                         36u
#define HIGHWAY_BIT_GAME_AT                                            37u
#define HIGHWAY_BIT_GAME_AT_PLY                                        38u
#define HIGHWAY_BIT_GAME_HAS_ECO                                       39u
#define HIGHWAY_BIT_GAME_HAS_MOTIF                                     40u
#define HIGHWAY_BIT_GAME_HAS_OPENING                                   41u
#define HIGHWAY_BIT_HAS_A                                              42u
#define HIGHWAY_BIT_HAS_AGE                                            43u
#define HIGHWAY_BIT_HAS_AST_CHILD                                      44u
#define HIGHWAY_BIT_HAS_AST_KIND                                       45u
#define HIGHWAY_BIT_HAS_ATTRIBUTE                                      46u
#define HIGHWAY_BIT_HAS_ATTRIBUTION                                    47u
#define HIGHWAY_BIT_HAS_BIDI_CLASS                                     48u
#define HIGHWAY_BIT_HAS_BLACK                                          49u
#define HIGHWAY_BIT_HAS_BLOCK                                          50u
#define HIGHWAY_BIT_HAS_CITATION                                       51u
#define HIGHWAY_BIT_HAS_CLOCK                                          52u
#define HIGHWAY_BIT_HAS_COMBINING_CLASS                                53u
#define HIGHWAY_BIT_HAS_CONTEXT                                        54u
#define HIGHWAY_BIT_HAS_DBPEDIA_RELATION                               55u
#define HIGHWAY_BIT_HAS_DEFINITION                                     56u
#define HIGHWAY_BIT_HAS_DOMAIN_REGION                                  57u
#define HIGHWAY_BIT_HAS_DOMAIN_TOPIC                                   58u
#define HIGHWAY_BIT_HAS_DOMAIN_USAGE                                   59u
#define HIGHWAY_BIT_HAS_EAST_ASIAN_WIDTH                               60u
#define HIGHWAY_BIT_HAS_ECO                                            61u
#define HIGHWAY_BIT_HAS_EMOJI_PROPERTY                                 62u
#define HIGHWAY_BIT_HAS_ETYMOLOGY                                      63u
#define HIGHWAY_BIT_HAS_EVAL                                           64u
#define HIGHWAY_BIT_HAS_EVAL_TOKEN                                     65u
#define HIGHWAY_BIT_HAS_EVENT                                          66u
#define HIGHWAY_BIT_HAS_EXAMPLE                                        67u
#define HIGHWAY_BIT_HAS_EXTERNAL_ID                                    68u
#define HIGHWAY_BIT_HAS_FEATURE                                        69u
#define HIGHWAY_BIT_HAS_FIRST_SUBEVENT                                 70u
#define HIGHWAY_BIT_HAS_FRAME                                          71u
#define HIGHWAY_BIT_HAS_FRAME_ELEMENT                                  72u
#define HIGHWAY_BIT_HAS_GENERAL_CATEGORY                               73u
#define HIGHWAY_BIT_HAS_HIDDEN_SIZE                                    74u
#define HIGHWAY_BIT_HAS_INTERMEDIATE_SIZE                              75u
#define HIGHWAY_BIT_HAS_ISO639_1_CODE                                  76u
#define HIGHWAY_BIT_HAS_ISO639_2B_CODE                                 77u
#define HIGHWAY_BIT_HAS_ISO639_2T_CODE                                 78u
#define HIGHWAY_BIT_HAS_ISO639_2_CODE                                  79u
#define HIGHWAY_BIT_HAS_JOINING_TYPE                                   80u
#define HIGHWAY_BIT_HAS_LANGUAGE                                       81u
#define HIGHWAY_BIT_HAS_LANGUAGE_SCOPE                                 82u
#define HIGHWAY_BIT_HAS_LANGUAGE_TYPE                                  83u
#define HIGHWAY_BIT_HAS_LAST_SUBEVENT                                  84u
#define HIGHWAY_BIT_HAS_LEX_CATEGORY                                   85u
#define HIGHWAY_BIT_HAS_LICENSE                                        86u
#define HIGHWAY_BIT_HAS_LINE_BREAK                                     87u
#define HIGHWAY_BIT_HAS_LOWERCASE_MAPPING                              88u
#define HIGHWAY_BIT_HAS_MEMBER                                         89u
#define HIGHWAY_BIT_HAS_MIRROR                                         90u
#define HIGHWAY_BIT_HAS_NAME                                           91u
#define HIGHWAY_BIT_HAS_NAME_ALIAS                                     92u
#define HIGHWAY_BIT_HAS_NUMERIC_TYPE                                   93u
#define HIGHWAY_BIT_HAS_NUMERIC_VALUE                                  94u
#define HIGHWAY_BIT_HAS_NUM_HEADS                                      95u
#define HIGHWAY_BIT_HAS_NUM_KV_HEADS                                   96u
#define HIGHWAY_BIT_HAS_NUM_LAYERS                                     97u
#define HIGHWAY_BIT_HAS_ONSET_SEGMENT                                  98u
#define HIGHWAY_BIT_HAS_PART                                           99u
#define HIGHWAY_BIT_HAS_PATCH                                          100u
#define HIGHWAY_BIT_HAS_POS                                            101u
#define HIGHWAY_BIT_HAS_PREREQUISITE                                   102u
#define HIGHWAY_BIT_HAS_PROPERTY                                       103u
#define HIGHWAY_BIT_HAS_RATING                                         104u
#define HIGHWAY_BIT_HAS_RECORDING                                      105u
#define HIGHWAY_BIT_HAS_REGION                                         106u
#define HIGHWAY_BIT_HAS_RESULT                                         107u
#define HIGHWAY_BIT_HAS_SCRIPT                                         108u
#define HIGHWAY_BIT_HAS_SEMANTIC_ROLE                                  109u
#define HIGHWAY_BIT_HAS_SENSE                                          110u
#define HIGHWAY_BIT_HAS_SOURCE_URL                                     111u
#define HIGHWAY_BIT_HAS_SPECTRAL_PEAK                                  112u
#define HIGHWAY_BIT_HAS_SUBEVENT                                       113u
#define HIGHWAY_BIT_HAS_SUBSTANCE                                      114u
#define HIGHWAY_BIT_HAS_SYNSET_KEY                                     115u
#define HIGHWAY_BIT_HAS_TC_CLASS                                       116u
#define HIGHWAY_BIT_HAS_TERMINATION                                    117u
#define HIGHWAY_BIT_HAS_THEMATIC_ROLE                                  118u
#define HIGHWAY_BIT_HAS_THINK_CLASS                                    119u
#define HIGHWAY_BIT_HAS_TIME_CONTROL                                   120u
#define HIGHWAY_BIT_HAS_TITLECASE_MAPPING                              121u
#define HIGHWAY_BIT_HAS_UPPERCASE_MAPPING                              122u
#define HIGHWAY_BIT_HAS_USAGE_REGISTER                                 123u
#define HIGHWAY_BIT_HAS_UTF8_ROLE                                      124u
#define HIGHWAY_BIT_HAS_VALENCE_PATTERN                                125u
#define HIGHWAY_BIT_HAS_VARIANT_OF                                     126u
#define HIGHWAY_BIT_HAS_VERB_FRAME                                     127u
#define HIGHWAY_BIT_HAS_VERSION                                        128u
#define HIGHWAY_BIT_HAS_VOCAB_SIZE                                     129u
#define HIGHWAY_BIT_HAS_WHITE                                          130u
#define HIGHWAY_BIT_HAS_XPOS                                           131u
#define HIGHWAY_BIT_INCHOATIVE_OF                                      132u
#define HIGHWAY_BIT_INHERITED_FROM                                     133u
#define HIGHWAY_BIT_INHERITS_FROM                                      134u
#define HIGHWAY_BIT_IN_VERB_GROUP_WITH                                 135u
#define HIGHWAY_BIT_IS_A                                               136u
#define HIGHWAY_BIT_IS_AFTER                                           137u
#define HIGHWAY_BIT_IS_ANTONYM_OF                                      138u
#define HIGHWAY_BIT_IS_AT_SAMPLE                                       139u
#define HIGHWAY_BIT_IS_BEFORE                                          140u
#define HIGHWAY_BIT_IS_COORDINATE_TERM_WITH                            141u
#define HIGHWAY_BIT_IS_EXAMPLE_OF                                      142u
#define HIGHWAY_BIT_IS_INSTANCE_OF                                     143u
#define HIGHWAY_BIT_IS_LANGUAGE_CODE                                   144u
#define HIGHWAY_BIT_IS_LEMMA_OF                                        145u
#define HIGHWAY_BIT_IS_PARTICIPLE_OF                                   146u
#define HIGHWAY_BIT_IS_PIXEL_OF                                        147u
#define HIGHWAY_BIT_IS_SENSE_OF                                        148u
#define HIGHWAY_BIT_IS_SIMILAR_TO                                      149u
#define HIGHWAY_BIT_IS_SYNONYM_OF                                      150u
#define HIGHWAY_BIT_IS_TRANSLATION_OF                                  151u
#define HIGHWAY_BIT_IS_TYPED_AS                                        152u
#define HIGHWAY_BIT_LOCATED_NEAR                                       153u
#define HIGHWAY_BIT_MADE_UP_OF                                         154u
#define HIGHWAY_BIT_MANNER_OF                                          155u
#define HIGHWAY_BIT_MEMBER_OF_MACROLANGUAGE                            156u
#define HIGHWAY_BIT_MEMBER_OF_VERBNET_CLASS                            157u
#define HIGHWAY_BIT_MERGES_WITH                                        158u
#define HIGHWAY_BIT_MOTIVATED_BY_GOAL                                  159u
#define HIGHWAY_BIT_MOVE                                               160u
#define HIGHWAY_BIT_MOVE_QUALITY                                       161u
#define HIGHWAY_BIT_NORMALIZES_TO                                      162u
#define HIGHWAY_BIT_NOT_CAPABLE_OF                                     163u
#define HIGHWAY_BIT_NOT_DESIRES                                        164u
#define HIGHWAY_BIT_NOT_HAS_PROPERTY                                   165u
#define HIGHWAY_BIT_NOT_USED_FOR                                       166u
#define HIGHWAY_BIT_OBJECT_USE                                         167u
#define HIGHWAY_BIT_OBSTRUCTED_BY                                      168u
#define HIGHWAY_BIT_ON_DATE                                            169u
#define HIGHWAY_BIT_OPENING_NAME                                       170u
#define HIGHWAY_BIT_OUTCOME                                            171u
#define HIGHWAY_BIT_OV_RELATES                                         172u
#define HIGHWAY_BIT_O_EFFECT                                           173u
#define HIGHWAY_BIT_O_REACT                                            174u
#define HIGHWAY_BIT_O_WANT                                             175u
#define HIGHWAY_BIT_PERSPECTIVE_ON                                     176u
#define HIGHWAY_BIT_PERTAINS_TO                                        177u
#define HIGHWAY_BIT_PLAYED_BY                                          178u
#define HIGHWAY_BIT_PRECEDES                                           179u
#define HIGHWAY_BIT_PRECEDES_IN_TIME                                   180u
#define HIGHWAY_BIT_RECEIVES_ACTION                                    181u
#define HIGHWAY_BIT_REFERENCES                                         182u
#define HIGHWAY_BIT_RELATED_TO                                         183u
#define HIGHWAY_BIT_REQUIRES                                           184u
#define HIGHWAY_BIT_ROLE_CORRESPONDS_TO                                185u
#define HIGHWAY_BIT_SEMANTIC_EQUIVALENCE                               186u
#define HIGHWAY_BIT_SIMILAR_TO                                         187u
#define HIGHWAY_BIT_SUPERSEDED_BY                                      188u
#define HIGHWAY_BIT_SYMBOL_OF                                          189u
#define HIGHWAY_BIT_TOKEN_MAPS_TO                                      190u
#define HIGHWAY_BIT_TRANSCRIBES_AS                                     191u
#define HIGHWAY_BIT_USED_FOR                                           192u
#define HIGHWAY_BIT_USES_SCRIPT                                        193u
#define HIGHWAY_BIT_USES_SCRIPT_EXTENSION                              194u
#define HIGHWAY_BIT_X_ATTR                                             195u
#define HIGHWAY_BIT_X_EFFECT                                           196u
#define HIGHWAY_BIT_X_FILLED_BY                                        197u
#define HIGHWAY_BIT_X_INTENT                                           198u
#define HIGHWAY_BIT_X_NEED                                             199u
#define HIGHWAY_BIT_X_REACT                                            200u
#define HIGHWAY_BIT_X_REASON                                           201u
#define HIGHWAY_BIT_X_WANT                                             202u

/* Band index constants */
#define HIGHWAY_BAND_MANDATE                                       0u
#define HIGHWAY_BAND_DEFINITIONAL                                  1u
#define HIGHWAY_BAND_TAXONOMIC                                     2u
#define HIGHWAY_BAND_EQUIVALENCE                                   3u
#define HIGHWAY_BAND_PARTITIVE                                     4u
#define HIGHWAY_BAND_CAUSAL                                        5u
#define HIGHWAY_BAND_OPPOSITIONAL                                  6u
#define HIGHWAY_BAND_ASSOCIATIVE                                   7u
#define HIGHWAY_BAND_TENSOR_CALCULATION                            8u
#define HIGHWAY_BAND_LEXICAL_GLUE                                  9u
#define HIGHWAY_BAND_SCALAR_VALUED                                 10u
#define HIGHWAY_BAND_STANDARDS_STRUCTURAL                          11u
#define HIGHWAY_BAND_PROBATIONARY                                  12u
