namespace Laplace.SeedTableGenerator;

using System;
using System.Globalization;
using System.IO;
using System.Text;

/// <summary>
/// Helpers for emitting C source / header files. Centralizes the formatting
/// rules (deterministic doubles, fixed-width hex bytes, license header) so
/// every emitter produces byte-identical output given identical input — a
/// requirement for reproducible substrate seeds.
/// </summary>
internal static class CHeaderWriter
{
    public const string LicenseBanner =
        "/*\n" +
        " * Generated by Laplace.SeedTableGenerator. Do NOT edit by hand.\n" +
        " * The substrate's content-addressed identity invariant requires\n" +
        " * this file to be byte-equivalent to a fresh regeneration from the\n" +
        " * same canonical source artifacts.\n" +
        " */\n\n";

    /// <summary>
    /// Format an IEEE 754 double using the round-trip "G17" form so the
    /// emitted text decodes back to the exact same bit pattern. Required
    /// for super-Fibonacci position deterministic reproduction.
    /// </summary>
    public static string FormatDouble(double v) =>
        v.ToString("G17", CultureInfo.InvariantCulture);

    /// <summary>
    /// Format a 32-byte hash as a brace-enclosed C array initializer.
    /// </summary>
    public static string FormatHashInit(ReadOnlySpan<byte> hash)
    {
        var sb = new StringBuilder(8 + hash.Length * 6);
        sb.Append('{');
        for (int i = 0; i < hash.Length; ++i)
        {
            if (i > 0) { sb.Append(','); }
            sb.Append("0x");
            sb.Append(hash[i].ToString("X2", CultureInfo.InvariantCulture));
        }
        sb.Append('}');
        return sb.ToString();
    }

    /// <summary>Open a writer with UTF-8 (no BOM) + LF line endings — stable cross-platform.</summary>
    public static StreamWriter OpenWriter(string path)
    {
        var stream = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None);
        return new StreamWriter(stream, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false))
        {
            NewLine = "\n",
        };
    }
}
