#define LAPLACE_GEOM_VERSION   '0.1.0'

#define LAPLACE_IMMUTABLE_STRICT  IMMUTABLE STRICT PARALLEL SAFE
#define LAPLACE_IMMUTABLE         IMMUTABLE        PARALLEL SAFE
#define LAPLACE_STABLE_STRICT     STABLE   STRICT  PARALLEL SAFE
#define LAPLACE_VOLATILE_STRICT   VOLATILE STRICT
