if(EXISTS "D:/Repositories/Laplace/build-win2/dynamics/tests/laplace_dynamics_tests[1]_tests.cmake")
  include("D:/Repositories/Laplace/build-win2/dynamics/tests/laplace_dynamics_tests[1]_tests.cmake")
else()
  add_test(laplace_dynamics_tests_NOT_BUILT laplace_dynamics_tests_NOT_BUILT)
endif()
