if(EXISTS "/home/ahart/Projects/Laplace-Legacy/recovery/native-build/engine/dynamics/tests/laplace_dynamics_tests[1]_tests.cmake")
  include("/home/ahart/Projects/Laplace-Legacy/recovery/native-build/engine/dynamics/tests/laplace_dynamics_tests[1]_tests.cmake")
else()
  add_test(laplace_dynamics_tests_NOT_BUILT laplace_dynamics_tests_NOT_BUILT)
endif()
