#!/bin/bash
#
# Drive a game against Laplace over the OpenAICompat /chess/play lane.
#
# The lane is stateful per session: start mints a session, each move is applied
# against the FEN you hand it, and finish folds the result into the substrate.
# This script keeps the FEN in a state file so a game can be played one move per
# invocation from a shell, a CI step or an agent.
#
#   scripts/chess-play.sh new [white|black]   start a session (default: you are white)
#   scripts/chess-play.sh move <uci>          play your move, print Laplace's reply
#   scripts/chess-play.sh go                  let Laplace move for the side to move
#   scripts/chess-play.sh fen                 print the current FEN
#   scripts/chess-play.sh finish <result>     result: "white wins" | "black wins" | "draw"
#
# Env: LAPLACE_API   endpoint            (default http://hart-server:8080)
#      LAPLACE_DEPTH search depth        (default 6)
#      CHESS_STATE   state file          (default /tmp/laplace-chess-$USER.state)
#
# Anything other than "white wins"/"black wins"/"draw" folds as a DRAW
# (ChessEngineService.ParseTerminalStatus), so a typo silently misrecords the
# game — the result is validated here rather than at the endpoint.

set -euo pipefail

API="${LAPLACE_API:-http://hart-server:8080}"
DEPTH="${LAPLACE_DEPTH:-6}"
STATE="${CHESS_STATE:-/tmp/laplace-chess-$USER.state}"
START_FEN="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"

die() { echo "$*" >&2; exit 1; }

# jq is not a hard dependency of this repo; fall back to grep for the few
# scalars we read so the script works on a bare runner.
field() { # field <json> <key>
    if command -v jq >/dev/null 2>&1; then
        printf '%s' "$1" | jq -r --arg k "$2" '.[$k] // empty'
    else
        printf '%s' "$1" | grep -o "\"$2\":\"[^\"]*\"" | head -1 | cut -d'"' -f4
    fi
}
flag() { printf '%s' "$1" | grep -o "\"$2\":[a-z]*" | head -1 | cut -d: -f2; }

post() { curl -sS -m 120 -X POST "$API$1" -H 'Content-Type: application/json' -d "$2"; }

# The state file is generated by save() below at runtime; there is nothing
# static for shellcheck to follow.
# shellcheck source=/dev/null
load() { [ -f "$STATE" ] || die "no session — run: $0 new"; . "$STATE"; }
# FEN contains spaces — the state file is sourced, so the values must be quoted
# or "w KQkq - 0 1" runs as a command and FEN keeps only the first token.
save() { printf 'SESSION=%s\nFEN="%s"\n' "$SESSION" "$1" > "$STATE"; }

# Print Laplace's reply and store the resulting FEN. effMu/rated say whether the
# move came out of consensus or fell back to plain alpha-beta, which is the whole
# point of watching this lane — a substrate read, not a search.
laplace_move() {
    local r fen
    r=$(post /chess/play/bestmove \
        "{\"sessionId\":\"$SESSION\",\"fen\":\"$1\",\"depth\":$DEPTH,\"substrate\":true}")
    echo "laplace: $r"
    fen=$(field "$r" fen)
    [ -n "$fen" ] || die "no fen in bestmove reply: $r"
    save "$fen"
    echo "fen: $fen"
    if [ "$(flag "$r" terminal)" = "true" ]; then
        echo "GAME OVER — $(field "$r" status)"
    fi
}

cmd="${1:-}"
case "$cmd" in
    new)
        side="${2:-white}"
        r=$(post /chess/play/start \
            "{\"record\":true,\"tenant\":\"public\",\"user\":\"$USER\"}")
        SESSION=$(field "$r" sessionId)
        [ -n "$SESSION" ] || die "start failed: $r"
        save "$START_FEN"
        echo "session: $SESSION"
        echo "game:    $(field "$r" gameId)   (routing handle, not a substrate entity)"
        if [ "$side" = "black" ]; then laplace_move "$START_FEN"; fi
        ;;

    move)
        [ $# -ge 2 ] || die "usage: $0 move <uci>"
        load
        r=$(post /chess/play/move "{\"sessionId\":\"$SESSION\",\"fen\":\"$FEN\",\"uci\":\"$2\"}")
        echo "you($2): $r"
        # An illegal move leaves the session untouched; do not advance the state
        # file or the next call would play from a position the server never saw.
        [ "$(flag "$r" legal)" = "true" ] || die "illegal move — position unchanged"
        fen=$(field "$r" fen)
        save "$fen"
        if [ "$(flag "$r" terminal)" = "true" ]; then
            echo "GAME OVER — $(field "$r" status)"
        else
            laplace_move "$fen"
        fi
        ;;

    go)
        load
        laplace_move "$FEN"
        ;;

    fen)
        load
        echo "$FEN"
        ;;

    finish)
        [ $# -ge 2 ] || die "usage: $0 finish \"white wins\"|\"black wins\"|draw"
        case "$2" in
            "white wins"|"black wins"|draw) ;;
            *) die "result must be \"white wins\", \"black wins\" or \"draw\" — anything else folds as a draw" ;;
        esac
        load
        post /chess/play/finish "{\"sessionId\":\"$SESSION\",\"status\":\"$2\",\"adjudicated\":false}"
        echo
        rm -f "$STATE"
        ;;

    *)
        sed -n '3,20p' "$0" | sed 's/^# \?//'
        exit 2
        ;;
esac
