#!/usr/bin/env python3
"""Install one canonical Laplace environment into operator shells and runner jobs."""

from __future__ import annotations

import argparse
import fcntl
import os
from pathlib import Path
import shlex
import stat
import tempfile


PROFILE_BEGIN = "# >>> Laplace environment >>>"
PROFILE_END = "# <<< Laplace environment <<<"
RUNNER_BEGIN = "# >>> laplace-runner managed: product environment >>>"
RUNNER_END = "# <<< laplace-runner managed: product environment <<<"


def replace_block(original: str, begin: str, end: str, block: str) -> str:
    start = original.find(begin)
    if start >= 0:
        finish = original.find(end, start)
        if finish < 0:
            raise ValueError(f"managed block starting with {begin!r} has no end marker")
        finish += len(end)
        if finish < len(original) and original[finish] == "\n":
            finish += 1
        return original[:start] + block + original[finish:]
    separator = "" if not original or original.endswith("\n") else "\n"
    if original and not original.endswith("\n\n"):
        separator += "\n"
    return original + separator + block


def atomic_write(
    path: Path, content: str, *, default_mode: int, allow_owned_file_update: bool = False
) -> bool:
    prior = path.lstat() if path.exists() or path.is_symlink() else None
    if prior is not None and not stat.S_ISREG(prior.st_mode):
        raise ValueError(f"refusing to replace non-regular file: {path}")
    encoded = content.encode("utf-8")
    if prior is not None and path.read_bytes() == encoded:
        return False
    # Runner homes deliberately deny directory writes to operator group members,
    # while their existing .env is group-writable. In that one case, update the
    # owned regular file under an exclusive lock instead of weakening the directory.
    if prior is not None and allow_owned_file_update and not os.access(path.parent, os.W_OK):
        descriptor = os.open(path, os.O_WRONLY | os.O_NOFOLLOW)
        try:
            fcntl.flock(descriptor, fcntl.LOCK_EX)
            os.ftruncate(descriptor, 0)
            view = memoryview(encoded)
            while view:
                view = view[os.write(descriptor, view):]
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as stream:
            if prior is not None:
                os.fchown(stream.fileno(), prior.st_uid, prior.st_gid)
            os.fchmod(stream.fileno(), stat.S_IMODE(prior.st_mode) if prior else default_mode)
            stream.write(encoded)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    return True


def shell_assignment(name: str, value: str) -> str:
    return f"export {name}={shlex.quote(value)}"


def configure_operator(
    home: Path,
    laplace_root: Path,
    refactor_root: Path,
    install_prefix: Path,
    public_base_url: str,
    default_agent: str,
) -> list[Path]:
    loader = home / ".config/shell/laplace.env"
    values = {
        "LAPLACE_ROOT": str(laplace_root),
        "LAPLACE_REFACTOR_ROOT": str(refactor_root),
        "LAPLACE_INSTALL_PREFIX": str(install_prefix),
        "LAPLACE_APP_DIR": str(install_prefix / "app"),
        "LAPLACE_DB": "Host=/var/run/postgresql;Username=laplace_admin;Database=laplace",
        "LAPLACE_AGENTS_CONFIG": str(install_prefix / "app/agents.json"),
        "LAPLACE_AGENT_DEFAULT": default_agent,
        "LAPLACE_PUBLIC_BASE_URL": public_base_url.rstrip("/"),
    }
    lines = [
        "# Generated by Laplace scripts/configure-laplace-environment.py.",
        "# Secret values remain in the single mode-0600 source below.",
        'if [ -r "$HOME/.config/shell/secrets.env" ]; then',
        "  _laplace_shell_flags=$-",
        "  set -a",
        '  . "$HOME/.config/shell/secrets.env"',
        '  case "$_laplace_shell_flags" in *a*) ;; *) set +a ;; esac',
        "  unset _laplace_shell_flags",
        "fi",
        'if [ -n "${LICHESS_API:-}" ] && [ -z "${LICHESS_TOKEN:-}" ]; then',
        '  export LICHESS_TOKEN="$LICHESS_API"',
        "fi",
        *(shell_assignment(name, value) for name, value in values.items()),
        "",
    ]
    changed = []
    if atomic_write(loader, "\n".join(lines), default_mode=0o600):
        changed.append(loader)

    profile_block = (
        f"{PROFILE_BEGIN}\n"
        '[ ! -r "$HOME/.config/shell/laplace.env" ] || . "$HOME/.config/shell/laplace.env"\n'
        f"{PROFILE_END}\n"
    )
    for name in (".zshrc", ".zprofile", ".bashrc", ".profile"):
        path = home / name
        original = path.read_text(encoding="utf-8") if path.exists() else ""
        updated = replace_block(original, PROFILE_BEGIN, PROFILE_END, profile_block)
        if atomic_write(path, updated, default_mode=0o644):
            changed.append(path)
    return changed


def configure_runner(
    path: Path,
    laplace_root: Path,
    refactor_root: Path,
    install_prefix: Path,
    public_base_url: str,
    default_agent: str,
) -> bool:
    values = {
        "LAPLACE_ROOT": str(laplace_root),
        "LAPLACE_REFACTOR_ROOT": str(refactor_root),
        "LAPLACE_INSTALL_PREFIX": str(install_prefix),
        "LAPLACE_APP_DIR": str(install_prefix / "app"),
        "LAPLACE_DB": "Host=/var/run/postgresql;Username=laplace_admin;Database=laplace",
        "LAPLACE_AGENTS_CONFIG": str(install_prefix / "app/agents.json"),
        "LAPLACE_AGENT_DEFAULT": default_agent,
        "LAPLACE_PUBLIC_BASE_URL": public_base_url.rstrip("/"),
    }
    block = "\n".join(
        [RUNNER_BEGIN, *(f"{name}={value}" for name, value in values.items()), RUNNER_END, ""]
    )
    original = path.read_text(encoding="utf-8") if path.exists() else ""
    updated = replace_block(original, RUNNER_BEGIN, RUNNER_END, block)
    return atomic_write(path, updated, default_mode=0o640, allow_owned_file_update=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--home", type=Path)
    parser.add_argument("--laplace-root", "--legacy-root", dest="laplace_root", type=Path)
    parser.add_argument("--refactor-root", type=Path)
    parser.add_argument("--install-prefix", type=Path, default=Path("/opt/laplace"))
    parser.add_argument("--public-base-url", default="https://hart-server:8443")
    parser.add_argument("--default-agent", default="gemini")
    parser.add_argument("--runner-env", type=Path)
    parser.add_argument("--skip-operator", action="store_true")
    args = parser.parse_args()

    if not args.skip_operator and not (args.home and args.laplace_root and args.refactor_root):
        parser.error("--home, --laplace-root and --refactor-root are required for operator setup")
    if args.skip_operator and not args.runner_env:
        parser.error("--skip-operator requires --runner-env")
    if args.runner_env and not (args.laplace_root and args.refactor_root):
        parser.error("--runner-env requires --laplace-root and --refactor-root")

    changed = []
    if not args.skip_operator:
        changed.extend(configure_operator(
            args.home,
            args.laplace_root,
            args.refactor_root,
            args.install_prefix,
            args.public_base_url,
            args.default_agent,
        ))
    if args.runner_env and configure_runner(
        args.runner_env,
        args.laplace_root,
        args.refactor_root,
        args.install_prefix,
        args.public_base_url,
        args.default_agent,
    ):
        changed.append(args.runner_env)
    for path in changed:
        print(path)


if __name__ == "__main__":
    main()
