#!/usr/bin/env python3
"""Generate docs/INVENTORY.md — the counted facts the prose docs cite.

The 2026-07-18 forest audit found every counted claim in prose (project count,
decomposer count, relation count, SQL family count) had silently drifted from
the tree. This script makes those facts a deterministic function of the source:
prose docs (README, CLAUDE.md, continuity) cite docs/INVENTORY.md instead of
embedding counts, and the CI policy job fails when the committed file no longer
matches a regeneration (same shape as the codegen determinism gate).

Write-if-changed; stdlib only; deterministic ordering throughout.

Usage: python3 scripts/docs-inventory.py [--check]
  --check  exit 1 if docs/INVENTORY.md is stale instead of rewriting it
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "INVENTORY.md"

CLASS_RX = re.compile(r"^\s*(?:public\s+|internal\s+)?(?:sealed\s+|abstract\s+|partial\s+|static\s+)*class\s+(\w+Decomposer)\b", re.M)


def solution_projects() -> tuple[list[str], list[str]]:
    text = (ROOT / "app" / "Laplace.slnx").read_text(encoding="utf-8")
    names = sorted(
        Path(m.group(1)).stem
        for m in re.finditer(r'<Project\s+Path="([^"]+)"', text)
    )
    tests = [n for n in names if n.endswith(".Tests")]
    prod = [n for n in names if not n.endswith(".Tests")]
    return prod, tests


def decomposer_classes(assembly_dir: Path) -> list[str]:
    found: set[str] = set()
    for cs in sorted(assembly_dir.rglob("*.cs")):
        found.update(CLASS_RX.findall(cs.read_text(encoding="utf-8", errors="replace")))
    return sorted(found)


def sql_families() -> list[str]:
    base = ROOT / "extension" / "laplace_substrate" / "sql" / "functions"
    return sorted(p.name for p in base.iterdir() if p.is_dir())


def native_sources() -> list[str]:
    base = ROOT / "extension" / "laplace_substrate" / "src"
    return sorted(p.name for p in base.glob("*.c"))


def relations() -> tuple[int, int, list[str]]:
    text = (ROOT / "engine" / "manifest" / "relation_types.toml").read_text(encoding="utf-8")
    count = len(re.findall(r"^\[\[relation\]\]", text, re.M))
    aliases = len(re.findall(r"^\[\[alias\]\]", text, re.M))
    ranks_block = re.search(r"^\[ranks\]\n(.*?)(?=^\[)", text, re.M | re.S)
    bands: list[str] = []
    if ranks_block:
        for line in ranks_block.group(1).splitlines():
            m = re.match(r"^(\w+)\s*=\s*[\d.]+", line.strip())
            if m:
                bands.append(m.group(1))
    return count, aliases, bands


def perfcache_blobs() -> list[str]:
    rx = re.compile(r"laplace_\w+_perfcache\.bin")
    hits: set[str] = set()
    for scope in ("engine", "extension", "scripts", "app"):
        for p in sorted((ROOT / scope).rglob("*")):
            if p.suffix.lower() in {".c", ".h", ".cpp", ".hpp", ".cs", ".cmd", ".ps1", ".sh", ".py", ".cmake", ".txt", ".in"} and p.is_file():
                hits.update(rx.findall(p.read_text(encoding="utf-8", errors="replace")))
    return sorted(hits)


def render() -> str:
    prod, tests = solution_projects()
    decomposers = decomposer_classes(ROOT / "app" / "Laplace.Decomposers")
    chess = decomposer_classes(ROOT / "app" / "Laplace.Chess")
    families = sql_families()
    natives = native_sources()
    rel_count, alias_count, bands = relations()
    blobs = perfcache_blobs()

    def bullets(items: list[str]) -> str:
        return "\n".join(f"- `{i}`" for i in items)

    return f"""# Inventory (GENERATED — do not edit)

Generated by `python3 scripts/docs-inventory.py` (Windows:
`scripts\\win\\docs-inventory.cmd`). The CI policy job regenerates this file and
fails on drift, so every count below is true for the commit you are reading.
Prose docs cite this file instead of embedding counts.

## Solution — {len(prod)} projects + {len(tests)} test projects (`app/Laplace.slnx`)

{bullets(prod)}

Test projects:

{bullets(tests)}

## Decomposers — {len(decomposers)} in `Laplace.Decomposers`, {len(chess)} in `Laplace.Chess`

{bullets(decomposers)}

Chess:

{bullets(chess)}

## SQL function families — {len(families)} (`extension/laplace_substrate/sql/functions/`)

{bullets(families)}

## Native extension sources — {len(natives)} (`extension/laplace_substrate/src/`)

{bullets(natives)}

## Relation manifest (`engine/manifest/relation_types.toml`)

- Governed canonical relations: **{rel_count}** (+{alias_count} aliases — aliases map to a canonical and add no highway bits)
- Salience bands: **{len(bands)}** — {", ".join(f"`{b}`" for b in bands)}

Highway bits are assigned alphabetically at codegen: adding a relation renumbers
bits and owes a reseed (see CLAUDE.md).

## Perfcache blobs referenced in source

{bullets(blobs)}
"""


def main() -> int:
    content = render()
    check = "--check" in sys.argv[1:]
    existing = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if existing == content:
        print(f"docs-inventory: {OUT.relative_to(ROOT)} up to date")
        return 0
    if check:
        print(f"docs-inventory: {OUT.relative_to(ROOT)} is STALE — run scripts/docs-inventory.py", file=sys.stderr)
        return 1
    OUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"docs-inventory: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
