#!/usr/bin/env python3
"""Derive engine/manifest/vocabulary/*.tsv, the governed linguistic vocabularies.

Every value comes from the authority that declares it; nothing here is a hand list.

  upos.tsv          UD universal POS tags        UD validator data/upos.json
  deprel.tsv        UD universal relations       UD validator data/udeprels.json
  deprel_subtype.tsv  subtypes of those relations  UD validator data/deprels.json (permitted)
  feature.tsv       morphological feature names  UD validator data/feats.json (permitted)
  feature_value.tsv feature values               UD validator data/feats.json (uvalues + lvalues)
  pos_alias.tsv     a source tagset's POS codes  each source's own declaration (below)

A relation label is a composition: "nsubj:pass" is the universal relation nsubj plus
the subtype pass. Which subtypes a language permits is the validator's testimony about
that language; it is ingested as claims, not frozen here.

Codes are append-only (ADR 0001). A refresh keeps every code already assigned, appends
new values after the highest code, and never removes a value: an occurrence packed
with a code decodes to the same value forever.

POS normalization: a source's code maps to a UPOS tag only where the source's own
declaration names that part of speech. A declared code without such a name stays the
source's own value (an empty upos column) and is recorded as unresolved.
"""
import argparse, hashlib, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "engine/manifest/vocabulary"

UD_TOOLS = Path("/vault/Data/.refresh-20260903/UD-Tools/10ce40cf8a577714e51cf56b443dd4c2c6d55f91/data")
WNDB = Path("/vault/Data/Wordnet/WordNet-3.0/doc/man/wndb.5")
FN_TYPES = Path("/vault/Data/FrameNet/framenet_v17/schema/commonTypes.xsd")
PB_DTD = Path("/vault/Data/PropBank/propbank-frames-main/dtds/v3.4/frameset.dtd")
WIKTEXTRACT_POS = Path.home() / ".local/lib/python3.10/site-packages/wiktextract/parts_of_speech.py"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_codes(path: Path, key_cols: int) -> dict:
    """Existing assignments: key tuple -> (code, rest columns)."""
    out = {}
    if not path.exists():
        return out
    lines = [l for l in path.read_text(encoding="utf-8").splitlines() if l and not l.startswith("#")]
    for line in lines[1:]:
        cols = line.split("\t")
        out[tuple(cols[1:1 + key_cols])] = int(cols[0])
    return out


def assign(path: Path, keys: list, key_cols: int) -> list:
    """Keep existing codes, append new keys in declaration order; never drop a key."""
    existing = read_codes(path, key_cols)
    codes = dict(existing)
    nxt = max(existing.values(), default=0) + 1
    for k in keys:
        if k not in codes:
            codes[k] = nxt
            nxt += 1
    return sorted(((c, k) for k, c in codes.items()), key=lambda ck: ck[0])


def write(path: Path, authorities: list, header: list, rows: list) -> None:
    lines = ["# Generated by scripts/refresh-vocabulary-manifest.py from the authorities below; do not edit."]
    lines += [f"# authority\t{p}\tsha256={sha256(p)}" for p in authorities]
    lines.append("\t".join(header))
    lines += ["\t".join(str(c) for c in r) for r in rows]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---- source POS declarations -------------------------------------------------------

def wordnet_codes() -> dict:
    """wndb(5WN) ss_type: one-character code -> the part of speech it names."""
    text = WNDB.read_text(encoding="utf-8")
    block = text[text.index(".I ss_type"):]
    return {m.group(1): m.group(2) for m in re.finditer(r"\\fB(\w)\\fP\t([A-Z ]+)\n", block[:600])}


def framenet_codes() -> list:
    text = FN_TYPES.read_text(encoding="utf-8")
    block = text[text.index('name="POSType"'):]
    block = block[:block.index("</xsd:simpleType>")]
    return re.findall(r'<xsd:enumeration value="([^"]+)"/>', block)


def propbank_codes() -> dict:
    """frameset.dtd: the alias pos enumeration and the glosses in the comment after it."""
    text = PB_DTD.read_text(encoding="utf-8")
    decl = re.search(r"<!ATTLIST alias\s+pos \(([^)]*)\)", text)
    codes = [c.strip() for c in decl.group(1).split("|")]
    gloss_block = text[decl.end():decl.end() + 800]
    glosses = dict(re.findall(r"^\s+(\w) = (.+)$", gloss_block, re.M))
    return {c: glosses.get(c, "").strip() for c in codes}


def wiktextract_codes() -> list:
    ns: dict = {}
    exec(compile(WIKTEXTRACT_POS.read_text(encoding="utf-8"), str(WIKTEXTRACT_POS), "exec"), ns)
    return sorted(ns["PARTS_OF_SPEECH"])


# The part of speech each source's declaration names, as the UPOS tag with that name
# (UD's upos.json lists the tags; universaldependencies.org/u/pos defines them).
# Keys are the names the source itself writes; a code whose name is not listed here
# (an idiom, an affix, a "MISSING IDK" code) is not a part of speech UPOS names.
WORDNET_NAMES = {"NOUN": "NOUN", "VERB": "VERB", "ADJECTIVE": "ADJ",
                 "ADJECTIVE SATELLITE": "ADJ", "ADVERB": "ADV"}
PROPBANK_NAMES = {"Adverb": "ADV", "Preposition": "ADP", "Verb": "VERB",
                  "Noun": "NOUN", "Adjective": "ADJ"}
# FrameNet's POSType codes abbreviate its part-of-speech names (FrameNet II book, lexical
# unit POS): A adjective, ADV adverb, ART article, CCON coordinating conjunction, INTJ
# interjection, N noun, NUM number, PREP preposition, PRON pronoun, SCON subordinating
# conjunction, V verb. C (conjunction of either kind), AVP (adverbial particle) and
# IDIO (idiom) name no single UPOS tag.
FRAMENET_NAMES = {"A": "ADJ", "ADV": "ADV", "ART": "DET", "CCON": "CCONJ", "INTJ": "INTJ",
                  "N": "NOUN", "NUM": "NUM", "PREP": "ADP", "PRON": "PRON", "SCON": "SCONJ",
                  "V": "VERB"}
# wiktextract part-of-speech codes (parts_of_speech.py). conj covers both coordinating
# and subordinating conjunctions and therefore names no single UPOS tag; affixes,
# phrases, characters and romanizations are not parts of speech.
WIKTIONARY_NAMES = {"noun": "NOUN", "verb": "VERB", "adj": "ADJ", "adv": "ADV", "name": "PROPN",
                    "pron": "PRON", "det": "DET", "article": "DET", "num": "NUM", "intj": "INTJ",
                    "prep": "ADP", "postp": "ADP", "circumpos": "ADP", "ambiposition": "ADP",
                    "particle": "PART", "punct": "PUNCT", "symbol": "SYM"}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ud-tools", type=Path, default=UD_TOOLS)
    args = ap.parse_args()
    ud = args.ud_tools
    OUT.mkdir(parents=True, exist_ok=True)

    upos = json.loads((ud / "upos.json").read_text())["upos"]
    rows = assign(OUT / "upos.tsv", [(t,) for t in upos], 1)
    write(OUT / "upos.tsv", [ud / "upos.json"], ["code", "label"], [(c, k[0]) for c, k in rows])
    upos_set = set(upos)

    udeprels = json.loads((ud / "udeprels.json").read_text())["udeprels"]
    rows = assign(OUT / "deprel.tsv", [(r,) for r in udeprels], 1)
    write(OUT / "deprel.tsv", [ud / "udeprels.json"], ["code", "label"], [(c, k[0]) for c, k in rows])

    deprels = json.loads((ud / "deprels.json").read_text())["deprels"]
    subtypes = sorted({part for rels in deprels.values() for label, info in rels.items()
                       if info.get("permitted") for part in label.split(":")[1:]})
    for rels in deprels.values():
        for label, info in rels.items():
            if info.get("permitted") and label.split(":")[0] not in udeprels:
                raise SystemExit(f"deprels.json permits {label}, whose head is not a universal relation")
    rows = assign(OUT / "deprel_subtype.tsv", [(s,) for s in subtypes], 1)
    write(OUT / "deprel_subtype.tsv", [ud / "deprels.json"], ["code", "subtype"], [(c, k[0]) for c, k in rows])

    feats = json.loads((ud / "feats.json").read_text())["features"]
    names, values = set(), set()
    for fs in feats.values():
        for name, info in fs.items():
            if not info.get("permitted"):
                continue
            names.add(name)
            for v in info.get("uvalues", []) + info.get("lvalues", []):
                values.add((name, v))
    rows = assign(OUT / "feature.tsv", [(n,) for n in sorted(names)], 1)
    write(OUT / "feature.tsv", [ud / "feats.json"], ["code", "feature"], [(c, k[0]) for c, k in rows])
    rows = assign(OUT / "feature_value.tsv", sorted(values), 2)
    write(OUT / "feature_value.tsv", [ud / "feats.json"], ["code", "feature", "value"],
          [(c, k[0], k[1]) for c, k in rows])

    aliases = []  # (tagset, code, upos or "")
    for code, name in sorted(wordnet_codes().items()):
        aliases.append(("wordnet", code, WORDNET_NAMES.get(name, "")))
    for code in framenet_codes():
        aliases.append(("framenet", code, FRAMENET_NAMES.get(code, "")))
    for code, gloss in propbank_codes().items():
        aliases.append(("propbank", code, PROPBANK_NAMES.get(gloss, "")))
    for code in wiktextract_codes():
        aliases.append(("wiktionary", code, WIKTIONARY_NAMES.get(code, "")))
    declared = {(t, c) for t, c, _ in aliases}
    for table, tagset in ((WORDNET_NAMES, None), (FRAMENET_NAMES, "framenet"), (WIKTIONARY_NAMES, "wiktionary")):
        if tagset:
            for code in table:
                if (tagset, code) not in declared:
                    raise SystemExit(f"{tagset} does not declare {code}")
    for _, _, u in aliases:
        if u and u not in upos_set:
            raise SystemExit(f"{u} is not a UPOS tag")
    write(OUT / "pos_alias.tsv", [WNDB, FN_TYPES, PB_DTD, WIKTEXTRACT_POS],
          ["tagset", "code", "upos"], aliases)

    for name in ("upos", "deprel", "deprel_subtype", "feature", "feature_value", "pos_alias"):
        n = sum(1 for l in (OUT / f"{name}.tsv").read_text().splitlines() if l and not l.startswith("#")) - 1
        print(f"{name}: {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
