#!/usr/bin/env python3
"""Derive engine/manifest/languages.tsv, the governed language vocabulary.

Every row maps a language tag (as sources write it) to its canonical ISO 639-3 Id and
names the authority that states the mapping:
  iso639-3     the Id itself                       (ISO 639-3 code table)
  iso639-1/2b/2t  Part1 / Part2B / Part2T aliases  (ISO 639-3 code table)
  iso639-3-retired  retired Id -> Change_To          (ISO 639-3 retirements)
  iana         deprecated subtag -> Preferred-Value (IANA language subtag registry)
  cldr         legacy/deprecated tag -> replacement (CLDR supplementalMetadata)
Chains resolve to the final 639-3 Id; a tag no authority maps is not listed.
"""
import csv, re, sys, xml.etree.ElementTree as ET
from pathlib import Path

root = Path(sys.argv[1] if len(sys.argv) > 1 else "/vault/Data/ISO639")
iso_dir = root / "iso-639-3_Code_Tables_20260415" / "iso-639-3_Code_Tables_20260415"
out = Path(__file__).resolve().parents[1] / "engine/manifest/languages.tsv"

ids, alias = set(), {}
for r in csv.DictReader(open(iso_dir / "iso-639-3.tab", encoding="utf-8-sig"), delimiter="\t"):
    i = r["Id"].strip(); ids.add(i); alias.setdefault(i, (i, "iso639-3"))
    for col, auth in (("Part1", "iso639-1"), ("Part2b", "iso639-2b"), ("Part2t", "iso639-2t")):
        v = r[col].strip()
        if v: alias.setdefault(v, (i, auth))
for r in csv.DictReader(open(iso_dir / "iso-639-3_Retirements.tab", encoding="utf-8-sig"), delimiter="\t"):
    old, new = r["Id"].strip(), r["Change_To"].strip()
    if old and new and old not in alias: alias[old] = (new, "iso639-3-retired")
reg = (root / "iana/language-subtag-registry.txt").read_text(encoding="utf-8").split("%%")
for rec in reg:
    f = dict(re.findall(r"^([A-Za-z-]+): (.*)$", rec, re.M))
    if f.get("Type") == "language" and "Preferred-Value" in f:
        alias.setdefault(f["Subtag"].lower(), (f["Preferred-Value"].lower(), "iana"))
for la in ET.parse(root / "cldr/supplementalMetadata.xml").getroot().iter("languageAlias"):
    t, rep = la.get("type", "").lower().replace("_", "-"), la.get("replacement", "").lower().split("_")[0]
    if t and rep and t not in alias: alias[t] = (rep, "cldr")

def final(tag, seen=()):
    target, _ = alias[tag]
    if target in ids: return target
    if target in alias and target not in seen: return final(target, seen + (tag,))
    return None

rows = sorted((t, final(t), a[1]) for t, a in alias.items() if final(t))
with open(out, "w", encoding="utf-8") as o:
    o.write("# Governed language vocabulary: tag -> canonical ISO 639-3 Id, with the stating authority.\n")
    o.write("# Generated by scripts/refresh-language-manifest.py from /vault/Data/ISO639 (ISO 639-3 20260415,\n")
    o.write("# IANA language subtag registry, CLDR supplementalMetadata). Do not edit by hand.\n")
    o.write("tag\tiso639_3\tauthority\n")
    for t, c, a in rows: o.write(f"{t}\t{c}\t{a}\n")
print(f"{len(rows)} tags -> {len(ids)} languages: {out}")
