#!/usr/bin/env python3
"""Pure host-bootstrap renderer: retain installed managed-service peer identities.

Generated output contract: the existing runner/postgres/operator map plus ONLY
the two known managed accounts when present. No HBA, files or services are changed.
"""
import argparse
import pwd
import re


def account_exists(name):
    try:
        pwd.getpwnam(name)
        return True
    except KeyError:
        return False


def render(operator="", exists=account_exists):
    if operator and not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_.-]{0,63}\$?", operator):
        raise ValueError("invalid operator account name")
    accounts = ["laplace-runner", "postgres"]
    if operator and operator not in accounts:
        accounts.append(operator)
    accounts.extend(name for name in ("laplace-mcp", "laplace-lichess") if exists(name) and name not in accounts)
    return "# Generated by scripts/render-pg-peer-map.py: installed local peer identities\n" + "".join(
        f"laplace_map   {account:16s} laplace_admin\n" for account in accounts)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--operator", default="")
    arguments = parser.parse_args()
    print(render(arguments.operator), end="")
