#!/usr/bin/env python3
"""Fail when local/tool/runtime artifacts or obvious live credentials are tracked.

The repository is source + intentional reproducible build inputs. Developer-local AI
configuration, session notes, host-specific wrappers, runtime evidence, build outputs,
logs, and credentials belong outside Git history. This gate operates on `git ls-files`,
so ignored local files remain local while anything committed must satisfy the source-tree
contract.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path, PurePosixPath

ALLOWED_ROOT_DOT_DIRS = {".github"}
ALLOWED_ROOT_DOT_FILES = {".gitignore", ".gitattributes"}

FORBIDDEN_PREFIXES = (
    ".github/archive/",
    "build/",
    "build-logs/",
    "engine/build/",
    "out/",
    "artifacts/",
    ".artifacts/",
    "web/node_modules/",
    "web/dist/",
    "web/storybook-static/",
    "app/Laplace.Endpoints.OpenAICompat/wwwroot/",
    "extension/results/",
    "extension/tmp_check/",
    "deploy/share/",
)

FORBIDDEN_EXACT = {
    "extension/regression.diffs",
    "extension/regression.out",
    # Generated by Microsoft.Extensions.ApiDescription.Server during the build.
    # Deploy consumes the freshly generated file; Git does not need a stale copy.
    "web/openapi/openapi.json",
    # Operator/host wrappers expose local machine names, filesystem layout and
    # personal corpus paths. Canonical cross-platform operations live under scripts/.
    "Claude_Bench.bat",
    "Tony.bat",
    "Tony_Hart-Desktop - Full.bat",
    "Tony_Hart-Desktop.bat",
    "Tony_Hart-Server.bat",
}

FORBIDDEN_SUFFIXES = (
    ".log",
    ".log.wall",
    ".log.time",
    ".tlog",
    ".trx",
    ".binlog",
    ".pdb",
    ".dll",
    ".so",
    ".dylib",
    ".perfcache",
    ".gguf",
    ".safetensors",
    ".onnx",
    ".sql.i",
    ".actual.json",
    ".dump",
    ".sql.gz",
)

# Strong signatures only. Do not turn ordinary words such as "token" or "password"
# into a noisy gate; those belong to a dedicated secret scanner if one is adopted.
SECRET_PATTERNS = (
    ("private key", re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----")),
    ("GitHub classic PAT", re.compile(r"\bghp_[A-Za-z0-9]{36,}\b")),
    ("GitHub fine-grained PAT", re.compile(r"\bgithub_pat_[A-Za-z0-9_]{50,}\b")),
    ("AWS access key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("Stripe live secret", re.compile(r"\bsk_live_[A-Za-z0-9]{16,}\b")),
    ("Slack token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}\b")),
)


def tracked_files() -> list[str]:
    raw = subprocess.check_output(["git", "ls-files", "-z"])
    return [p.decode("utf-8", "surrogateescape") for p in raw.split(b"\0") if p]


def path_violation(path: str) -> str | None:
    posix = PurePosixPath(path)
    first = posix.parts[0] if posix.parts else ""

    # Root hidden directories are executable/configuration trust surfaces. Keep the
    # GitHub CI directory; everything else must be explicitly reviewed before tracking.
    if len(posix.parts) > 1 and first.startswith(".") and first not in ALLOWED_ROOT_DOT_DIRS:
        return f"developer-local hidden directory is tracked: {first}/"

    # Root hidden files are also fail-closed. Only VCS metadata policy is source.
    if len(posix.parts) == 1 and first.startswith(".") and first not in ALLOWED_ROOT_DOT_FILES:
        return "developer/tool-local root dotfile is tracked"

    if path in FORBIDDEN_EXACT:
        return "generated/runtime/operator-local artifact is tracked"
    if any(path.startswith(prefix) for prefix in FORBIDDEN_PREFIXES):
        return "build/runtime/archive path is tracked"
    if any(path.endswith(suffix) for suffix in FORBIDDEN_SUFFIXES):
        return "build/log/runtime artifact is tracked"
    return None


def secret_violations(path: str) -> list[str]:
    p = Path(path)
    try:
        if p.stat().st_size > 2_000_000:
            return []
        data = p.read_bytes()
        if b"\0" in data:
            return []
        text = data.decode("utf-8", "ignore")
    except (OSError, UnicodeError):
        return []
    return [name for name, pattern in SECRET_PATTERNS if pattern.search(text)]


def main() -> int:
    violations: list[str] = []
    for path in tracked_files():
        reason = path_violation(path)
        if reason:
            violations.append(f"{path}: {reason}")
        for secret in secret_violations(path):
            violations.append(f"{path}: possible {secret}")

    if violations:
        print("repository hygiene gate FAILED", file=sys.stderr)
        for violation in violations:
            print(f"  - {violation}", file=sys.stderr)
        print(
            "Move local/runtime material outside the repository or explicitly amend the "
            "reviewed allowlist when the file is a required reproducible source input.",
            file=sys.stderr,
        )
        return 1

    print("repository hygiene gate: tracked tree contains source/approved CI only")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
