# CMake generated Testfile for 
# Source directory: /home/ahart/Projects/Laplace-Legacy/extension/laplace_substrate/tests
# Build directory: /home/ahart/Projects/Laplace-Legacy/recovery/native-build/extension/laplace_substrate/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[regress_setup_laplace_substrate]=] "/usr/bin/bash" "-c" "\"/opt/laplace/pgsql-18/bin/dropdb\" -U laplace_admin --if-exists laplace_regress_substrate && \"/opt/laplace/pgsql-18/bin/createdb\" -U laplace_admin -O laplace_admin laplace_regress_substrate")
set_tests_properties([=[regress_setup_laplace_substrate]=] PROPERTIES  FIXTURES_SETUP "regress_db_substrate" LABELS "regress;regress_fixture" _BACKTRACE_TRIPLES "/home/ahart/Projects/Laplace-Legacy/extension/laplace_substrate/tests/CMakeLists.txt;16;add_test;/home/ahart/Projects/Laplace-Legacy/extension/laplace_substrate/tests/CMakeLists.txt;0;")
add_test([=[regress_teardown_laplace_substrate]=] "/opt/laplace/pgsql-18/bin/dropdb" "-U" "laplace_admin" "--if-exists" "laplace_regress_substrate")
set_tests_properties([=[regress_teardown_laplace_substrate]=] PROPERTIES  FIXTURES_CLEANUP "regress_db_substrate" LABELS "regress;regress_fixture" _BACKTRACE_TRIPLES "/home/ahart/Projects/Laplace-Legacy/extension/laplace_substrate/tests/CMakeLists.txt;25;add_test;/home/ahart/Projects/Laplace-Legacy/extension/laplace_substrate/tests/CMakeLists.txt;0;")
add_test([=[regress_laplace_substrate]=] "/opt/laplace/pgsql-18/lib/pgxs/src/test/regress/pg_regress" "--bindir=/usr/lib/postgresql/18/bin" "--inputdir=/home/ahart/Projects/Laplace-Legacy/extension/laplace_substrate/tests" "--outputdir=/home/ahart/Projects/Laplace-Legacy/recovery/native-build/extension/laplace_substrate/tests/regress_output" "--dbname=laplace_regress_substrate" "--user=laplace_admin" "--use-existing" "bootstrap" "glicko2_aggregate" "entities_exist_bitmap" "consensus_signed" "consensus_upsert" "explore_web_neighbors" "attestation_merge" "generation_corpus" "steer_semantic_precedence" "converse" "chat_loop" "word_law" "identity_law" "schema_law" "structural_surface" "walk_richer_forward_pass" "chess_read" "chess_ranked_scope" "chess_player_identity_scope" "chess_fold_debt_repair" "ops_reads" "ops_control" "ingest_throughput" "walk_edge_weight_parity" "belief_distribution" "realize_ladder_parity" "display_label" "search_path_independence" "evict_source" "prompt_election" "apply_epoch" "walk_symmetry" "highway_mask_deposit")
set_tests_properties([=[regress_laplace_substrate]=] PROPERTIES  FIXTURES_REQUIRED "regress_db_substrate" LABELS "regress" _BACKTRACE_TRIPLES "/home/ahart/Projects/Laplace-Legacy/extension/laplace_substrate/tests/CMakeLists.txt;33;add_test;/home/ahart/Projects/Laplace-Legacy/extension/laplace_substrate/tests/CMakeLists.txt;0;")
