<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Laplace.Engine.Core</RootNamespace>
    <AssemblyName>Laplace.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Laplace.Substrate" />
    <InternalsVisibleTo Include="Laplace.Core.Tests" />
    <InternalsVisibleTo Include="Laplace.Substrate.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../engine/core/grammars/**/queries/tags.scm">
      <LogicalName>Laplace.GrammarTags.owned.%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="../../external/tree-sitter-grammars/**/queries/tags.scm">
      <LogicalName>Laplace.GrammarTags.external.%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
